define DEFAULT_TABLESPACE_TABLE = CWH;
define DEFAULT_TABLESPACE_INDEX = CWH_NDX;

CREATE SEQUENCE STC_ORDERS_NOT_IN_SYNC_SEQ
MINVALUE 1
MAXVALUE 99999999999999
START WITH 1
INCREMENT BY 1
NOCACHE;


CREATE TABLE STC_ORDERS_NOT_IN_SYNC (
  ID NUMBER(10) NOT NULL,
  ORDERNUMBER VARCHAR2(50) NOT NULL,
  GI_STATUS_CODE VARCHAR2(1) NOT NULL,
  GI_STATUS_NAME VARCHAR2(20) NOT NULL)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_ORDERS_NOT_IN_SYNC 
ADD CONSTRAINT PK_STC_ORDERS_NOT_IN_SYNC PRIMARY KEY (ID)
USING INDEX 
TABLESPACE &DEFAULT_TABLESPACE_INDEX;


