define DEFAULT_TABLESPACE_TABLE = CWE;
define DEFAULT_TABLESPACE_INDEX = CWE_NDX;

create table STC_ORDER_TYPE_STATUS_DISABLED(
	ORDERTYPE varchar2(25) not null,
	ORDERSTATUS varchar2(50) not null,
	constraint PK_STC_OTYPE_STATUS_DISABLED primary key(ORDERTYPE, ORDERSTATUS) using index
	(create unique index PK_STC_OTYPE_STATUS_DISABLED on STC_ORDER_TYPE_STATUS_DISABLED(ORDERTYPE, ORDERSTATUS) tablespace &DEFAULT_TABLESPACE_INDEX)
)
tablespace &DEFAULT_TABLESPACE_TABLE;


insert into STC_ORDER_TYPE_STATUS_DISABLED(ORDERTYPE, ORDERSTATUS) values ('T', 'REVISE');
insert into STC_ORDER_TYPE_STATUS_DISABLED(ORDERTYPE, ORDERSTATUS) values ('F', 'REVISE');
insert into STC_ORDER_TYPE_STATUS_DISABLED(ORDERTYPE, ORDERSTATUS) values ('T', 'CANCEL');
insert into STC_ORDER_TYPE_STATUS_DISABLED(ORDERTYPE, ORDERSTATUS) values ('E', 'CANCEL');

commit;
