/***

define DEFAULT_TABLESPACE_TABLE = CWE;
define DEFAULT_TABLESPACE_INDEX = CWE_NDX;

***/


define DEFAULT_TABLESPACE_TABLE = STC_DATA;
define DEFAULT_TABLESPACE_INDEX = STC_DATA;

drop table STC_ORDER_REJECTED_FOR_LOCK;

create table STC_ORDER_REJECTED_FOR_LOCK (
  ORDERNUMBER varchar2(50) not null
)
tablespace &DEFAULT_TABLESPACE_TABLE;

