--Insert all needed  block parameters configuration values for SMR 4927
insert into STC_BLOCKPARAMS_CONFIGURATION (CWDOCID,ISMANDATORY,BLOCKPARAMETERNAME,ORDERSTATUS,SERVICETYPE,ORDERTYPE) values ('1281000',null,'Add or Change Destination  Circuits','Cancel','IPVPN','C');
insert into STC_BLOCKPARAMS_CONFIGURATION (CWDOCID,ISMANDATORY,BLOCKPARAMETERNAME,ORDERSTATUS,SERVICETYPE,ORDERTYPE) values ('1281001',null,'Add or Change Destination  Circuits','New','IPVPN','C');
insert into STC_BLOCKPARAMS_CONFIGURATION (CWDOCID,ISMANDATORY,BLOCKPARAMETERNAME,ORDERSTATUS,SERVICETYPE,ORDERTYPE) values ('1281002',null,'Add or Change Destination  Circuits','Revise','IPVPN','C');
insert into STC_BLOCKPARAMS_CONFIGURATION (CWDOCID,ISMANDATORY,BLOCKPARAMETERNAME,ORDERSTATUS,SERVICETYPE,ORDERTYPE) values ('1281003',null,'Remove Destination Circuits','New','IPVPN','C');
insert into STC_BLOCKPARAMS_CONFIGURATION (CWDOCID,ISMANDATORY,BLOCKPARAMETERNAME,ORDERSTATUS,SERVICETYPE,ORDERTYPE) values ('1364000',null,'Remove Destination Circuits','Cancel','IPVPN','C');
insert into STC_BLOCKPARAMS_CONFIGURATION (CWDOCID,ISMANDATORY,BLOCKPARAMETERNAME,ORDERSTATUS,SERVICETYPE,ORDERTYPE) values ('1281005',null,'Remove Destination Circuits','Revise','IPVPN','C');

commit;
