define DEFAULT_TABLESPACE_TABLE = CWE;
define DEFAULT_TABLESPACE_INDEX = CWE_NDX;

create table STC_ORDER_UNDER_MGMT(
	ORDERNUMBER varchar2(50) not null,
	constraint PK_STC_ORDER_UNDER_MGMT primary key(ORDERNUMBER) using index
	(create unique index PK_STC_ORDER_UNDER_MGMT on STC_ORDER_UNDER_MGMT(ORDERNUMBER) tablespace &DEFAULT_TABLESPACE_INDEX)
)
tablespace &DEFAULT_TABLESPACE_TABLE;