define DEFAULT_TABLESPACE_TABLE = CWH;
define DEFAULT_TABLESPACE_INDEX = CWH_NDX;

drop table STC_NVPAIR_DUPLORDER;
create table STC_NVPAIR_DUPLORDER (
  NAME VARCHAR2(100) NOT NULL,
  SERVICETYPE VARCHAR2(25) NOT NULL)
tablespace &DEFAULT_TABLESPACE_TABLE;

alter table STC_NVPAIR_DUPLORDER 
add constraint PK_STC_NVPAIR_DUPLORDER primary key (NAME, SERVICETYPE)
using index 
tablespace &DEFAULT_TABLESPACE_INDEX;