define DEFAULT_TABLESPACE_TABLE = CWH;
define DEFAULT_TABLESPACE_INDEX = CWH_NDX;


CREATE TABLE STC_TMP_ARCHIVABLE_ORDER(
	ORDERNUMBER VARCHAR2(50),
	PARENTORDERNUMBER VARCHAR2(50),
	CWDOCID VARCHAR2(16) NOT NULL,
	WHENADDED DATE,
	CONSTRAINT PK_STC_TMP_ARCHIVABLE_ORDER PRIMARY KEY(CWDOCID) USING INDEX
	(CREATE UNIQUE INDEX PK_STC_TMP_ARCHIVABLE_ORDER ON STC_TMP_ARCHIVABLE_ORDER(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

