create or replace view STC_INSERTORDER_SITE as
 select SITE_INST_ID, SITE_HUM_ID, STATUS, CLLI, NUM, BASE_NUM, LATITUDE, LONGITUDE, RESTRICTIONS, CONTACTS, COMMENTS, ADDRESS, CITY, STATE_PROV, POST_CODE_1, POST_CODE_2, FLOOR, ROOM, NPA_NXX, COUNTY, COUNTRY, INST_VER
   from SITE_INST@RMS_PROD_DB_LINK
  where upper(STATUS) in ('IN SERVICE');