insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DDN', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SD', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('XP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DSB', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('PLL', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('TGP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('I-E2E-W', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DSLSKY', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('CBLSMW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('VPLSMW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('PtMP MW GTW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SIPMW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SATPtP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SIP1', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('IBBS (IRY473)', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DPC', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('FBR', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DBS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('PE-UPLINK', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('MVPN', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('NI-COMP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DIAL', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SMW4-MS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SDH GTW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('FOREIGN BACKHAUL', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('P', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('AW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('RP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('NP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('TD', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SONET Link', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('NOPX', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('P1', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('BORDER-MS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('ATMMVPN', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('PLLMW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('FTTM_LINK', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SATNET', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('INTERCONNECT LINK', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SM-Path', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SMW3-MS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('IBBS-IND117', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('IP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('IIC', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('ATM', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DSLAM', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('VST', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DUM', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('CBLS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('FOT-MS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('N-E2E-W', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('VGW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('IBBS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('BPLLMW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('REPEATOR_MW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('FLAG-MS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('Ring Service', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('APN GTW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DLL', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('D', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('FAC', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('RK', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DPD', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('IIP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('CNS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('PBX', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('BLSR', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('NALL', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('BMVPN', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DIASMW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('BPLL', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('PtMP UPLINK', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('TFR', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('IBBS (KKIA- Wi-Fi)', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('BWDM', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('FRN', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('AAC', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('T', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('PM', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SKY', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SKH', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('Transmission Segment', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('CM', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('NTT', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('MDIA', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DIAS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('BVPLSMW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SATIP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('IBBS (IRY407)', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('NPEERING', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('Capacity converter', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SA', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DPM', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('XD', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('GEF', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SLA', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('APN', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('VSATPtP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('MS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DSK', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('IBBS (KKIA-Wi-Fi)', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('DIA', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('TP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('PA', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('RPM', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('BLS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('VPLS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('SIP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('IGW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('IIPO', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('ECS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('POP UPLINK', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('WDM', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('IPMW', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('BSIP', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('MLS', null, null);
insert into stc_insertorder_servicetype (SERVICETYPE, DESCRIPTION, ADDITIONAL_INFO) values ('IMEWE-MS', null, null);
