update TEMPLATES_CONFIGURATION 
   set NVP_NAME = 'GRAN-X' 
 where SERVICE_TYPE = 'DSLSKY'
   and TEMPLATE_NAME = 'CIM-EBU-DSLSKY-MIGRATION'
   and NVP_NAME = 'GRAN-551_X'
   and NVP_VALUE_CRITERION = 'Y'
;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'DSLSKY', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'MVPN', 'New', 'CIM-EBU-MVPN-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'MVPN', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'DIAL', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'DIAL', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'DLL', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'DLL', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'FAC', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'FAC', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'IP', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'IP', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'PLL', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'PLL', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'D', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'D', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'DIA', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'DIA', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'IGW', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'IGW', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'IPMW', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'IPMW', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'MDIA', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'MDIA', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'NOPX', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'NOPX', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'P', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'P', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'PLLMW', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'PLLMW', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'SD', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'SD', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'TGP', 'New', 'CIM-EBU-GENR-MIGRATION', 'GRAN-X', 'Y' from TEMPLATES_CONFIGURATION;

insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'TGP', 'New', 'WOT-000-MASTER-INSTALL', null, null from TEMPLATES_CONFIGURATION;

commit;
