update STC_SKIP_WOSU
   set NV_PAIR_NAME = 'GRAN-X'
 where SERVICETYPE = 'DSLSKY'
   and NV_PAIR_NAME = 'GRAN-551_X';

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'MVPN', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'DIAL', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'DLL', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'FAC', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'IP', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'PLL', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'D', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'DIA', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'IGW', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'IPMW', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'MDIA', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'NOPX', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'P', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'PLLMW', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'SD', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, NV_PAIR_NAME, NV_PAIR_VALUE) 
select max(to_number(CWDOCID))+1, 1, 'TGP', 'GRAN-X', 'Y'from STC_SKIP_WOSU;

commit;
