create or replace view stc_bi_summary_report_v as
select prn.prn_name,
       prn.customer_name,
       prn.customer_project,
       prn.requirement_type,
       prn.quantity,
       prn.site_a_name,
       prn.site_a_if,
       prn.site_z_name,
       prn.site_z_if,
       prn.traffic_type,
       prn.remarks,
       tfr.tfr_id,
       tfr.tfr_number,
       tfr.project,
       bi.bi_id,
       bi.bi_status,
       bi.ring_name,
       bi.site_name,
       bi.network_type,
       bi.details,
       bi.category,
       bi.mop_number,
       bi.mop1_status,
       bi.mop2_status,
       bi.mop3_status,
       bi.mop_issue_date,
       bi.mop_impl_status,
       bi.mop_impl_compl_date,
       bi.mop_impl_estim_date,
       bi.contractor1,
       bi.contractor2,
       bi.contractor3,
       bi.last_fwd_dept,
       bi.last_fwd_eng,
       bi.creation_date,
       bi.sow_number,
       bi.sow1_status,
       bi.sow2_status,
       bi.sow3_status,
       bi.sow_issue_date
  from tfs.stc_bi bi, tfs.stc_bi_relationship bir, tfs.stc_prn prn, tfs.stc_tfr tfr
 where bir.bi_id = bi.bi_id
   and prn.prn_id = bir.source_prn_id
   and bir.source_tfr_id = '-1'
   and prn.tfr_id = tfr.tfr_id (+)
union
select prn.prn_name,
       prn.customer_name,
       prn.customer_project,
       prn.requirement_type,
       prn.quantity,
       prn.site_a_name,
       prn.site_a_if,
       prn.site_z_name,
       prn.site_z_if,
       prn.traffic_type,
       prn.remarks,
       tfr.tfr_id,
       tfr.tfr_number,
       tfr.project,
       bi.bi_id,
       bi.bi_status,
       bi.ring_name,
       bi.site_name,
       bi.network_type,
       bi.details,
       bi.category,
       bi.mop_number,
       bi.mop1_status,
       bi.mop2_status,
       bi.mop3_status,
       bi.mop_issue_date,
       bi.mop_impl_status,
       bi.mop_impl_compl_date,
       bi.mop_impl_estim_date,
       bi.contractor1,
       bi.contractor2,
       bi.contractor3,
       bi.last_fwd_dept,
       bi.last_fwd_eng,
       bi.creation_date,
       bi.sow_number,
       bi.sow1_status,
       bi.sow2_status,
       bi.sow3_status,
       bi.sow_issue_date
  from tfs.stc_bi bi, tfs.stc_bi_relationship bir, tfs.stc_tfr tfr, tfs.stc_prn prn
 where bir.bi_id = bi.bi_id
   and tfr.tfr_id = bir.source_tfr_id
   and bir.source_prn_id = '-1'
   and prn.prn_id (+) = tfr.prn_id;