create or replace view stc_tx_summary_report_v as
select prnr.prnr_id,
       prnr.prnr_name,
       prnr.prnr_status,
       prnr.customer_name,
       prnr.customer_project,
       prnr.customer_project_phase,
       prnr.creation_date prnr_creation_date,
       prnr.site_a_name,
       prnr.site_z_name,
       prnr.gsm_cell_id,
       prnr.gsm_cell_vendor,
       prn.prn_id,
       prn.prn_name,
       prn.prn_status,
       prn.requirement_type,
       prn.quantity,
       prn.plan_type,
       prn.issue,
       prn.planner,
       prn.site_a_mpls_device,
       prn.site_z_mpls_device,
       prn.pe_agg_slot,
       prn.pe_agg_port,
       prn.pe_agg_odf,
       tfr.tfr_id,
       tfr.tfr_number,
       tfr.tfr_status,
       tfr.dept_created_by,
       tfr.fa_completion_date
  from tfs.stc_prnr prnr, tfs.stc_prn prn, tfs.stc_tfr tfr
 where prnr.prnr_id = prn.prnr_id
   and tfr.tfr_id (+) = prn.tfr_id;