@define_variables.sql

DROP TABLE STCW_BUNDLEORDER_HEADER;
CREATE TABLE STCW_BUNDLEORDER_HEADER(
	CUSTOMERIDNUMBER VARCHAR2(50),
	ACCOUNTNUMBER VARCHAR2(50),
	CUSTOMERTYPE VARCHAR2(50),
	CUSTOMERIDTYPE VARCHAR2(50),
	CUSTOMERCONTACT VARCHAR2(256),
	CUSTOMERCONTACTNAME VARCHAR2(50),
	CUSTOMERNAME VARCHAR2(50),
	CUSTOMERNUMBER VARCHAR2(50),
	ORDERNUMBER VARCHAR2(50),
	ORDERTYPE VARCHAR2(1),
	ORDERSTATUS VARCHAR2(100),
	CREATIONDATE DATE,
	CREATEDBY VARCHAR2(50),
	CREATEDBYNAME VARCHAR2(50),
	CREATEDBYCONTACTNAME VARCHAR2(50),
	SERVICEDATE DATE,
	PRIORITY VARCHAR2(25),
	CUSTOMERSEGMENTATION VARCHAR2(30),
	FEASIBILITYFOR VARCHAR2(20),
	RESERVATION VARCHAR2(1),
	BUSINESSUNIT VARCHAR2(20),
	ICMSSALESORDERNUMBER VARCHAR2(100),
	REFERENCETELNUMBER VARCHAR2(100),
	SALESREPRESENTATIVE VARCHAR2(100),
	COMPLETIONDATE DATE,
	RECEIVEDATE DATE,
	ISMIGRATED NUMBER(1),
	CWDOCID VARCHAR2(16) NOT NULL,
	CWDOCSTAMP VARCHAR2(9),
	CWORDERCREATIONDATE DATE,
	CWORDERID VARCHAR2(16),
	CWPARENTID VARCHAR2(16),
	LASTUPDATEDDATE DATE,
	UPDATEDBY VARCHAR2(64),
	CONSTRAINT PK_STCW_BUNDLEORDER_HEADER PRIMARY KEY(CWDOCID) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_BUNDLEORDER_HEADER ON STCW_BUNDLEORDER_HEADER(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STCW_BUNDLEORDER_HEADER
ADD CONSTRAINT STCW_BO_HEADER_ORDERNUMBER UNIQUE (ORDERNUMBER) USING INDEX 
TABLESPACE &DEFAULT_TABLESPACE_INDEX;
  
CREATE INDEX STCW_BO_HEADER_CWORDERID ON STCW_BUNDLEORDER_HEADER (CWORDERID)
TABLESPACE &DEFAULT_TABLESPACE_INDEX;


