@define_variables.sql

DROP TABLE STCW_NAMEVALUE;
CREATE TABLE STCW_NAMEVALUE(
	NAME VARCHAR2(100),
	VALUE VARCHAR2(4000),
	NVACTION VARCHAR2(10),
	ISVAS VARCHAR2(1),
	PARENTELEMENTID VARCHAR2(16),
	CWDOCSTAMP VARCHAR2(9),
	CWORDERCREATIONDATE DATE,
	CWORDERID VARCHAR2(16),
	CWPARENTID VARCHAR2(16),
	LASTUPDATEDDATE DATE,
	UPDATEDBY VARCHAR2(64),
	CWDOCID VARCHAR2(16) NOT NULL,
	CONSTRAINT PK_STCW_NAMEVALUE PRIMARY KEY(CWDOCID) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_NAMEVALUE ON STCW_NAMEVALUE(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;


CREATE INDEX STCW_NAMEVALUE_PARENTID ON STCW_NAMEVALUE (PARENTELEMENTID)
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

CREATE INDEX STCW_NAMEVALUE_CWORDERID on STCW_NAMEVALUE (CWORDERID)
TABLESPACE &DEFAULT_TABLESPACE_INDEX;


