@define_variables.sql

DROP TABLE STCW_OH_VALIDATION_MAP;
CREATE TABLE STCW_OH_VALIDATION_MAP(
	ORDERTYPE VARCHAR2(1) NOT NULL,
	CUSTOMERIDNUMBER NUMBER(1),
	ACCOUNTNUMBER NUMBER(1),
	CUSTOMERTYPE NUMBER(1),
	CUSTOMERIDTYPE NUMBER(1),
	CUSTOMERCONTACT NUMBER(1),
	CUSTOMERCONTACTNAME NUMBER(1),
	CUSTOMERNAME NUMBER(1),
	CUSTOMERNUMBER NUMBER(1),
	CREATEDBYNAME NUMBER(1),
	CREATEDBYCONTACTNAME NUMBER(1),
	PRIORITY NUMBER(1),
	CUSTOMERSEGMENTATION NUMBER(1),
	FEASIBILITYFOR NUMBER(1),
	RESERVATION NUMBER(1),
	ICMSSALESORDERNUMBER NUMBER(1),
	REFERENCETELNUMBER NUMBER(1),
	SALESREPRESENTATIVE NUMBER(1),
	CONSTRAINT PK_STCW_OH_VALIDATION_MAP PRIMARY KEY(ORDERTYPE) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_OH_VALIDATION_MAP ON STCW_OH_VALIDATION_MAP(ORDERTYPE) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;
