@define_variables.sql

DROP TABLE STCW_ORDER_ORCHESTRATION;
CREATE TABLE STCW_ORDER_ORCHESTRATION(
	ORDERNUMBER VARCHAR2(50),
	CWORDERID VARCHAR2(16),
	CWPARENTOBJECTID VARCHAR2(16),
	SEQUENCE NUMBER(3),
	CWORDERITEMPATH VARCHAR2(1000),
	PROVISIONABLE NUMBER(1),
	CWDOCID VARCHAR2(16) NOT NULL,
	LINEITEMIDENTIFIER VARCHAR2(255),
	ELEMENTTYPEINORDERTREE VARCHAR2(1),
	ORCHESTRATIONPROCESSID NUMBER(16),
	PROVISIONINGPROCESSRESULT VARCHAR2(2),
	PROVISIONINGPROCESSID NUMBER(16),
	CONSTRAINT PK_STCW_ORDER_ORCHESTRATION PRIMARY KEY(CWDOCID) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_ORDER_ORCHESTRATION ON STCW_ORDER_ORCHESTRATION(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

CREATE INDEX STCW_ORD_ORCHESTR_CWORDERID ON STCW_ORDER_ORCHESTRATION (CWORDERID)
TABLESPACE &DEFAULT_TABLESPACE_INDEX;


