@define_variables.sql

DROP TABLE STCW_WORKORDERTYPE_MAP;
CREATE TABLE STCW_WORKORDERTYPE_MAP(
	ORDERTYPE VARCHAR2(1) NOT NULL,
	LINEITEMACTION VARCHAR2(10) NOT NULL,
	WORKORDERTYPE VARCHAR2(1) NOT NULL,
	CONSTRAINT PK_STCW_WORKORDERTYPE_MAP PRIMARY KEY(ORDERTYPE,LINEITEMACTION) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_WORKORDERTYPE_MAP ON STCW_WORKORDERTYPE_MAP(ORDERTYPE,LINEITEMACTION) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;
