@define_variables.sql

DROP TABLE STCW_COM_TO_GRANITE_DATA;
CREATE TABLE STCW_COM_TO_GRANITE_DATA(
	COM_NAME VARCHAR2(100) NOT NULL,
	COM_ELEMENT VARCHAR2(2) NOT NULL,
	GI_NAME VARCHAR2(100) NOT NULL,
	GI_ELEMENT VARCHAR2(2) NOT NULL,
	CIM VARCHAR2(1) NOT NULL,
	O_Q VARCHAR2(1) NOT NULL,
	CONSTRAINT PK_STCW_COM_TO_GRANITE_DATA PRIMARY KEY(COM_NAME, COM_ELEMENT, GI_NAME, GI_ELEMENT, CIM, O_Q) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_COM_TO_GRANITE_DATA ON STCW_COM_TO_GRANITE_DATA(COM_NAME, COM_ELEMENT, GI_NAME, GI_ELEMENT, CIM, O_Q) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;
  
CREATE INDEX STCW_COM_TO_GRANITE_DATA_IDX ON STCW_COM_TO_GRANITE_DATA (COM_ELEMENT, GI_ELEMENT, CIM, O_Q)
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

ALTER TABLE STCW_COM_TO_GRANITE_DATA ADD CONSTRAINT COM_ELEMENT_CHK CHECK (COM_ELEMENT IN ('OH', 'LI'));
ALTER TABLE STCW_COM_TO_GRANITE_DATA ADD CONSTRAINT GI_ELEMENT_CHK CHECK (GI_ELEMENT IN ('OH', 'LI'));
ALTER TABLE STCW_COM_TO_GRANITE_DATA ADD CONSTRAINT CIM_CHK CHECK (CIM IN ('W', 'E'));
ALTER TABLE STCW_COM_TO_GRANITE_DATA ADD CONSTRAINT O_Q_CHK CHECK (O_Q IN ('O', 'Q'));