@define_variables.sql

DROP TABLE STCW_GRANITE_EVENT_STORAGE;
CREATE TABLE STCW_GRANITE_EVENT_STORAGE(
	PROCESSID NUMBER(16),
	MSGTYPE VARCHAR2(10),
	GRANITEMSG LONG,
	CWDOCID VARCHAR2(16) NOT NULL,
	WHEN_INSERTED DATE,
	CONSTRAINT PK_STCW_GRANITE_EVENT_STORAGE PRIMARY KEY(CWDOCID) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_GRANITE_EVENT_STORAGE ON STCW_GRANITE_EVENT_STORAGE(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;
