@define_variables.sql

DROP TABLE STCW_NVNAMES_MANDATORY;
CREATE TABLE STCW_NVNAMES_MANDATORY(
  CWDOCID VARCHAR2(16) NOT NULL,
	ORDERTYPE VARCHAR2(1) NOT NULL,
	SERVICETYPE VARCHAR2(25) NOT NULL,
	NAMENVPAIR VARCHAR2(100) NOT NULL,
	CONSTRAINT PK_STCW_NVNAMES_MANDATORY PRIMARY KEY(CWDOCID) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_NVNAMES_MANDATORY ON STCW_NVNAMES_MANDATORY(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STCW_NVNAMES_MANDATORY
  ADD CONSTRAINT UK_STCW_NVNAMES_MANDATORY UNIQUE (ORDERTYPE, SERVICETYPE, NAMENVPAIR)
  USING INDEX 
  TABLESPACE &DEFAULT_TABLESPACE_INDEX;
