@define_variables.sql

DROP TABLE STCW_PRODUCTCODE;
CREATE TABLE STCW_PRODUCTCODE(
  PRODUCTCODE VARCHAR2(255) NOT NULL,
	CONSTRAINT PK_STCW_PRODUCTCODE PRIMARY KEY(PRODUCTCODE) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_PRODUCTCODE ON STCW_PRODUCTCODE(PRODUCTCODE) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

