@define_variables.sql

DROP TABLE STCW_SERVICETYPE_NAME_MAP;
CREATE TABLE STCW_SERVICETYPE_NAME_MAP(
  COM_SERVICETYPE VARCHAR2(25) NOT NULL,
  GI_SERVICETYPE VARCHAR2(25) NOT NULL,
	CONSTRAINT PK_STCW_SERVICETYPE_NAME_MAP PRIMARY KEY(COM_SERVICETYPE) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_SERVICETYPE_NAME_MAP ON STCW_SERVICETYPE_NAME_MAP(COM_SERVICETYPE) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

