@define_variables.sql

DROP TABLE STCW_PRIORITY_MAP;
CREATE TABLE STCW_PRIORITY_MAP(
  CWDOCID VARCHAR2(16) NOT NULL,
  SERVICETYPE VARCHAR2(25) NOT NULL,
  REASONCODE VARCHAR2(255),
  PRODUCTCODE VARCHAR2(255) NOT NULL,
  ORDERTYPE VARCHAR2(1) NOT NULL,
  PRIORITY NUMBER(2) NOT NULL,
	CONSTRAINT PK_STCW_PRIORITY_MAP PRIMARY KEY(CWDOCID) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_PRIORITY_MAP ON STCW_PRIORITY_MAP (CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STCW_PRIORITY_MAP
  ADD CONSTRAINT UK_STCW_PRIORITY_MAP UNIQUE (SERVICETYPE, REASONCODE, PRODUCTCODE, ORDERTYPE)
  USING INDEX 
  TABLESPACE &DEFAULT_TABLESPACE_INDEX;
