@define_variables.sql

DROP TABLE STCW_BU_PROVISIONING;
CREATE TABLE STCW_BU_PROVISIONING(
  SERVICETYPE VARCHAR2(25) NOT NULL,
  PRODUCTCODE VARCHAR2(255) NOT NULL,
  CIM VARCHAR2(1) NOT NULL,
	CONSTRAINT PK_STCW_BU_PROVISIONING PRIMARY KEY(SERVICETYPE, PRODUCTCODE, CIM) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_BU_PROVISIONING ON STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STCW_BU_PROVISIONING ADD CONSTRAINT CIM_BU_PROV_CHK CHECK (CIM IN ('E', 'W'));
