@define_variables.sql

DROP TABLE STCW_ATTR_SAME_VAL_IN_UPDATE;
CREATE TABLE STCW_ATTR_SAME_VAL_IN_UPDATE(
  ELEMENT_TYPE VARCHAR2(2) NOT NULL,
  IS_CANCEL NUMBER(1) NOT NULL,
  ATTRIBUTE_NAME VARCHAR2(100) NOT NULL,
	CONSTRAINT PK_STCW_ATTR_SAME_VAL_IN_UPD PRIMARY KEY(ELEMENT_TYPE, IS_CANCEL, ATTRIBUTE_NAME) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_ATTR_SAME_VAL_IN_UPD ON STCW_ATTR_SAME_VAL_IN_UPDATE (ELEMENT_TYPE, IS_CANCEL, ATTRIBUTE_NAME) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STCW_ATTR_SAME_VAL_IN_UPDATE ADD CONSTRAINT SAME_UPD_ELEMENTTYPE_CHK CHECK (ELEMENT_TYPE IN ('OH', 'LI'));
