@define_variables.sql

DROP TABLE STCW_NEWATTR_NVPAIR;
CREATE TABLE STCW_NEWATTR_NVPAIR(
	NAME VARCHAR2(100) NOT NULL,
	CONSTRAINT PK_STCW_NEWATTR_NVPAIR PRIMARY KEY(NAME) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_NEWATTR_NVPAIR ON STCW_NEWATTR_NVPAIR(NAME) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

