prompt Importing table STCW_WORKORDERTYPE_MAP...

insert into STCW_WORKORDERTYPE_MAP (ORDERTYPE, LINEITEMACTION, WORKORDERTYPE) values ('I', 'A', 'I');
insert into STCW_WORKORDERTYPE_MAP (ORDERTYPE, LINEITEMACTION, WORKORDERTYPE) values ('I', 'C', 'I');
insert into STCW_WORKORDERTYPE_MAP (ORDERTYPE, LINEITEMACTION, WORKORDERTYPE) values ('I', 'M', 'I');

insert into STCW_WORKORDERTYPE_MAP (ORDERTYPE, LINEITEMACTION, WORKORDERTYPE) values ('C', 'A', 'I');
insert into STCW_WORKORDERTYPE_MAP (ORDERTYPE, LINEITEMACTION, WORKORDERTYPE) values ('C', 'D', 'O');
insert into STCW_WORKORDERTYPE_MAP (ORDERTYPE, LINEITEMACTION, WORKORDERTYPE) values ('C', 'M', 'C');
insert into STCW_WORKORDERTYPE_MAP (ORDERTYPE, LINEITEMACTION, WORKORDERTYPE) values ('C', 'C', 'C');

insert into STCW_WORKORDERTYPE_MAP (ORDERTYPE, LINEITEMACTION, WORKORDERTYPE) values ('O', 'D', 'O');

insert into STCW_WORKORDERTYPE_MAP (ORDERTYPE, LINEITEMACTION, WORKORDERTYPE) values ('F', 'A', 'F');
insert into STCW_WORKORDERTYPE_MAP (ORDERTYPE, LINEITEMACTION, WORKORDERTYPE) values ('F', 'C', 'F');
insert into STCW_WORKORDERTYPE_MAP (ORDERTYPE, LINEITEMACTION, WORKORDERTYPE) values ('F', 'M', 'F');
insert into STCW_WORKORDERTYPE_MAP (ORDERTYPE, LINEITEMACTION, WORKORDERTYPE) values ('F', 'D', 'O');

commit;

prompt Done.


