select * from STCW_PICKLIST_FOR_VALIDATION
minus
select * from STCW_PICKLIST_FOR_VALIDATION@CWW_EOC16PROD_LINK;


select * from STCW_WORKORDERTYPE_MAP
minus
select * from STCW_WORKORDERTYPE_MAP@CWW_EOC16PROD_LINK;


select * from STCW_COM_TO_GRANITE_DATA
minus
select * from STCW_COM_TO_GRANITE_DATA@CWW_EOC16PROD_LINK;


select * from STCW_COM_TO_GRANITE_DATA
minus
select * from STCW_COM_TO_GRANITE_DATA@CWW_EOC16PROD_LINK;


select * from STCW_OH_VALIDATION_MAP
minus
select * from STCW_OH_VALIDATION_MAP@CWW_EOC16PROD_LINK;


select * from STCW_PRODUCTCODE
minus
select * from STCW_PRODUCTCODE@CWW_EOC16PROD_LINK;


select * from STCW_SERVICETYPE_NAME_MAP
minus
select * from STCW_SERVICETYPE_NAME_MAP@CWW_EOC16PROD_LINK;


select * from STCW_BU_PROVISIONING
minus
select * from STCW_BU_PROVISIONING@CWW_EOC16PROD_LINK;


select * from STCW_LINEITEM_VALIDATION_MAP
minus
select * from STCW_LINEITEM_VALIDATION_MAP@CWW_EOC16PROD_LINK;


select * from STCW_ATTR_SAME_VAL_IN_UPDATE
minus
select * from STCW_ATTR_SAME_VAL_IN_UPDATE@CWW_EOC16PROD_LINK;
