insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('C004','C100','W');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('C006','C100','W');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('C057','C057','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('C100','C100','W');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('CL003','CL003','W');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('D050','D050','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('D051','D051','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('D052','D052','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('D053','D053','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('D054','D054','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('D054','D100','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('D055','D055','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('D055','D100','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('D056','D056','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('D058','D058','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('D058','D101','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('D100','D100','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('D101','D101','E');
insert into STCW_BU_PROVISIONING(servicetype, productcode, cim) values ('DTEST','DTEST','W');

commit;
