-- STCW_PRODUCTCODE
update STCW_PRODUCTCODE set PRODUCTCODE = 'C032' where PRODUCTCODE = 'C32E';
update STCW_PRODUCTCODE set PRODUCTCODE = 'C033' where PRODUCTCODE = 'C33E';
update STCW_PRODUCTCODE set PRODUCTCODE = 'C034' where PRODUCTCODE = 'C34E';
update STCW_PRODUCTCODE set PRODUCTCODE = 'C035' where PRODUCTCODE = 'C35E';

delete from STCW_PRODUCTCODE where PRODUCTCODE in (
'C37O',
'C38O',
'C39O',
'C40O');

-- STCW_SERVICETYPE_NAME_MAP
delete from STCW_SERVICETYPE_NAME_MAP where COM_SERVICETYPE in (
'C32E',
'C34E',
'C33E',
'C35E',
'C37O',
'C38O',
'C39O',
'C40O');

insert into STCW_SERVICETYPE_NAME_MAP (COM_SERVICETYPE, GI_SERVICETYPE) values ('C032', 'C032');
insert into STCW_SERVICETYPE_NAME_MAP (COM_SERVICETYPE, GI_SERVICETYPE) values ('C033', 'C033');
insert into STCW_SERVICETYPE_NAME_MAP (COM_SERVICETYPE, GI_SERVICETYPE) values ('C034', 'C034');
insert into STCW_SERVICETYPE_NAME_MAP (COM_SERVICETYPE, GI_SERVICETYPE) values ('C035', 'C035');

-- STCW_BU_PROVISIONING
delete from STCW_BU_PROVISIONING where PRODUCTCODE in ('C31E', 'C36O') and SERVICETYPE in (
'C32E',
'C34E',
'C33E',
'C35E',
'C37O',
'C38O',
'C39O',
'C40O');

insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C032', 'C31E', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C033', 'C31E', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C034', 'C31E', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C035', 'C31E', 'W');

insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C032', 'C36O', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C033', 'C36O', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C034', 'C36O', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C035', 'C36O', 'W');

-- STCW_SERVICETYPES_HIERARCHY
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C032' where CHILD_SERVICETYPE = 'C32E' and PARENT_SERVICETYPE = 'C31E';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C033' where CHILD_SERVICETYPE = 'C33E' and PARENT_SERVICETYPE = 'C31E';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C034' where CHILD_SERVICETYPE = 'C34E' and PARENT_SERVICETYPE = 'C31E';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C035' where CHILD_SERVICETYPE = 'C35E' and PARENT_SERVICETYPE = 'C31E';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C032' where CHILD_SERVICETYPE = 'C37O' and PARENT_SERVICETYPE = 'C36O';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C033' where CHILD_SERVICETYPE = 'C38O' and PARENT_SERVICETYPE = 'C36O';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C034' where CHILD_SERVICETYPE = 'C39O' and PARENT_SERVICETYPE = 'C36O';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C035' where CHILD_SERVICETYPE = 'C40O' and PARENT_SERVICETYPE = 'C36O';

commit;
