-- STCW_PRODUCTCODE
update STCW_PRODUCTCODE set PRODUCTCODE = 'C32E' where PRODUCTCODE = 'C032';
update STCW_PRODUCTCODE set PRODUCTCODE = 'C33E' where PRODUCTCODE = 'C033';
update STCW_PRODUCTCODE set PRODUCTCODE = 'C34E' where PRODUCTCODE = 'C034';
update STCW_PRODUCTCODE set PRODUCTCODE = 'C35E' where PRODUCTCODE = 'C035';

insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C37O', 0, 'DEFAULT', 0);
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C38O', 0, 'DEFAULT', 0);
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C39O', 0, 'DEFAULT', 0);
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C40O', 0, 'DEFAULT', 0);

-- STCW_SERVICETYPE_NAME_MAP
delete from STCW_SERVICETYPE_NAME_MAP where COM_SERVICETYPE in (
'C032',
'C034',
'C033',
'C035');

insert into STCW_SERVICETYPE_NAME_MAP(COM_SERVICETYPE, GI_SERVICETYPE) values ('C32E', 'C32E');
insert into STCW_SERVICETYPE_NAME_MAP(COM_SERVICETYPE, GI_SERVICETYPE) values ('C33E', 'C33E');
insert into STCW_SERVICETYPE_NAME_MAP(COM_SERVICETYPE, GI_SERVICETYPE) values ('C34E', 'C34E');
insert into STCW_SERVICETYPE_NAME_MAP(COM_SERVICETYPE, GI_SERVICETYPE) values ('C35E', 'C35E');
insert into STCW_SERVICETYPE_NAME_MAP(COM_SERVICETYPE, GI_SERVICETYPE) values ('C37O', 'C37O');
insert into STCW_SERVICETYPE_NAME_MAP(COM_SERVICETYPE, GI_SERVICETYPE) values ('C38O', 'C38O');
insert into STCW_SERVICETYPE_NAME_MAP(COM_SERVICETYPE, GI_SERVICETYPE) values ('C39O', 'C39O');
insert into STCW_SERVICETYPE_NAME_MAP(COM_SERVICETYPE, GI_SERVICETYPE) values ('C40O', 'C40O');

-- STCW_BU_PROVISIONING
delete from STCW_BU_PROVISIONING where PRODUCTCODE in ('C31E', 'C36O') and SERVICETYPE in (
'C032E',
'C034E',
'C033E',
'C035E');

insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C32E', 'C31E', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C33E', 'C31E', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C34E', 'C31E', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C35E', 'C31E', 'W');

insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C37O', 'C36O', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C38O', 'C36O', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C39O', 'C36O', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C40O', 'C36O', 'W');

-- STCW_SERVICETYPES_HIERARCHY
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C32E' where CHILD_SERVICETYPE = 'C032' and PARENT_SERVICETYPE = 'C31E';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C33E' where CHILD_SERVICETYPE = 'C033' and PARENT_SERVICETYPE = 'C31E';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C34E' where CHILD_SERVICETYPE = 'C034' and PARENT_SERVICETYPE = 'C31E';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C35E' where CHILD_SERVICETYPE = 'C035' and PARENT_SERVICETYPE = 'C31E';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C37O' where CHILD_SERVICETYPE = 'C032' and PARENT_SERVICETYPE = 'C36O';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C38O' where CHILD_SERVICETYPE = 'C033' and PARENT_SERVICETYPE = 'C36O';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C39O' where CHILD_SERVICETYPE = 'C034' and PARENT_SERVICETYPE = 'C36O';
update STCW_SERVICETYPES_HIERARCHY set CHILD_SERVICETYPE = 'C40O' where CHILD_SERVICETYPE = 'C035' and PARENT_SERVICETYPE = 'C36O';

commit;
