insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C31E', 1, 'ALL_OR_NOTHING', 1);
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C32E', 0, 'DEFAULT', 0);
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C33E', 0, 'DEFAULT', 0);
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C34E', 0, 'DEFAULT', 0);
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C35E', 0, 'DEFAULT', 0);
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C36O', 1, 'ALL_OR_NOTHING', 1);
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C37O', 0, 'DEFAULT', 0);
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C38O', 0, 'DEFAULT', 0);
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C39O', 0, 'DEFAULT', 0);
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS) values ('C40O', 0, 'DEFAULT', 0);

commit;
