insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C31E', 'C31E', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C32E', 'C31E', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C33E', 'C31E', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C34E', 'C31E', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C35E', 'C31E', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C36O', 'C36O', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C37O', 'C36O', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C38O', 'C36O', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C39O', 'C36O', 'W');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('C40O', 'C36O', 'W');

commit;
