insert into STCW_SERVICETYPES_HIERARCHY(CWDOCID, PARENT_SERVICETYPE, CHILD_SERVICETYPE) values (1, 'C31E', 'C32E');
insert into STCW_SERVICETYPES_HIERARCHY(CWDOCID, PARENT_SERVICETYPE, CHILD_SERVICETYPE) values (2, 'C31E', 'C33E');
insert into STCW_SERVICETYPES_HIERARCHY(CWDOCID, PARENT_SERVICETYPE, CHILD_SERVICETYPE) values (3, 'C31E', 'C34E');
insert into STCW_SERVICETYPES_HIERARCHY(CWDOCID, PARENT_SERVICETYPE, CHILD_SERVICETYPE) values (4, 'C31E', 'C35E');
insert into STCW_SERVICETYPES_HIERARCHY(CWDOCID, PARENT_SERVICETYPE, CHILD_SERVICETYPE) values (5, 'C36O', 'C37O');
insert into STCW_SERVICETYPES_HIERARCHY(CWDOCID, PARENT_SERVICETYPE, CHILD_SERVICETYPE) values (6, 'C36O', 'C38O');
insert into STCW_SERVICETYPES_HIERARCHY(CWDOCID, PARENT_SERVICETYPE, CHILD_SERVICETYPE) values (7, 'C36O', 'C39O');
insert into STCW_SERVICETYPES_HIERARCHY(CWDOCID, PARENT_SERVICETYPE, CHILD_SERVICETYPE) values (8, 'C36O', 'C40O');

commit;
