define DEFAULT_TABLESPACE_TABLE = STC_DATA;
define DEFAULT_TABLESPACE_INDEX = STC_DATA;


DROP TABLE STCW_PICKLIST_FOR_VALIDATION;
CREATE TABLE STCW_PICKLIST_FOR_VALIDATION(
	CWDOCID VARCHAR2(16) NOT NULL,
	DATATYPENAME VARCHAR2(100),
	VALUE VARCHAR2(100),
	CONSTRAINT PK_STCW_PICKLIST_FOR_VALIDATIO PRIMARY KEY(CWDOCID) USING INDEX
	(CREATE UNIQUE INDEX PK_STCW_PICKLIST_FOR_VALIDATIO ON STCW_PICKLIST_FOR_VALIDATION(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STCW_PICKLIST_FOR_VALIDATION 
ADD CONSTRAINT UK_STCW_PKLIST_VALID UNIQUE (DATATYPENAME, VALUE) 
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

