-- accountStatus
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(1, 'accountStatus', 'Active');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(2, 'accountStatus', 'Inactive');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(3, 'accountStatus', 'Pending');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(4, 'accountStatus', 'Prospect');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(5, 'accountStatus', 'Write-Off');

-- accountSubType
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(6, 'accountSubType', 'OLO');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(7, 'accountSubType', 'POP');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(8, 'accountSubType', 'AA');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(9, 'accountSubType', 'Telecom');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(10, 'accountSubType', 'TV');

-- accountType
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(11, 'accountType', 'Business');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(12, 'accountType', 'Business Sales');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(13, 'accountType', 'Company');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(14, 'accountType', 'Consortium');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(15, 'accountType', 'Corporate');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(16, 'accountType', 'Customer');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(17, 'accountType', 'Department');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(18, 'accountType', 'Division');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(19, 'accountType', 'Government');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(20, 'accountType', 'Holding');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(21, 'accountType', 'Key Account');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(22, 'accountType', 'Other Licensed Opertor');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(23, 'accountType', 'Parent Company');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(24, 'accountType', 'Primary Sales');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(25, 'accountType', 'Service Provider');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(26, 'accountType', 'Subsidiary');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(27, 'accountType', 'Vendor');

-- changeRequestType
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(28, 'changeRequestType', 'RELOCATION');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(29, 'changeRequestType', 'UPGRADE');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(30, 'changeRequestType', 'DOWNGRADE');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(31, 'changeRequestType', 'CHG_TECH');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(32, 'changeRequestType', 'SUBMARINE_CABLE_CHANGE');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(33, 'changeRequestType', 'ASSOCIATE');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(34, 'changeRequestType', 'DISSOCIATE');

-- segmentFlag
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(35, 'segmentFlag', 'I');
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE) VALUES(36, 'segmentFlag', 'N');

commit;

