insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) values (1, 'I', 'D054', 'NO-CHG PRIMARY NAME',  0);
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D054', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D054', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D054', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D054', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D054', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D054', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D054', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D054', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D054', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D054', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D054', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D054', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D054', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D054', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D054', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D054', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D054', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D054', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D054', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D054', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D054', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D054', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D054', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D055', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D055', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D055', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D055', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D055', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D055', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D055', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D055', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D055', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D055', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D055', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D055', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D055', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D055', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D055', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D055', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D055', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D055', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D055', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D055', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D055', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D055', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D055', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D055', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D056', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D056', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D056', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D056', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D056', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D056', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D056', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D056', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D056', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D056', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D056', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D056', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D056', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D056', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D056', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D056', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D056', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D056', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D056', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D056', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D056', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D056', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D056', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D056', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D058', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D058', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D058', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D058', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D058', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'I', 'D058', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D058', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D058', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D058', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D058', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D058', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'F', 'D058', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) values max(to_number(cwdocid)) + 1, 'C', 'D058', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D058', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D058', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D058', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D058', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'C', 'D058', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D058', 'NO-CHG PRIMARY NAME',  0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D058', 'DEL PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D058', 'ADD PRIMARY VPN', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D058', 'NO-CHG VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D058', 'DEL VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;
insert into STCW_BLOCKPARAMS_CONFIGURATION(CWDOCID, ORDERTYPE, SERVICETYPE, BLOCKPARAMETERNAME, ISMANDATORY) select max(to_number(cwdocid)) + 1, 'D', 'D058', 'ADD VPN NAME', 0 from STCW_BLOCKPARAMS_CONFIGURATION;

commit;
