insert into TEMPLATES_CONFIGURATION(ID, ORDER_TYPE, SERVICE_CATEGORY, SERVICE_TYPE, ORDER_STATUS, TEMPLATE_NAME, NVP_NAME, NVP_VALUE_CRITERION)
select max(ID)+1, 'I', '*', 'DSLSKY', 'New', 'CIM-EBU-DSLSKY-MIGRATION', 'GRAN-551_X', 'Y' from TEMPLATES_CONFIGURATION;

