/***

define DEFAULT_TABLESPACE_TABLE = CWW;
define DEFAULT_TABLESPACE_INDEX = CWW_NDX;
define PE_TABLESPACE_TABLE = CWW;
define PE_TABLESPACE_INDEX = CWW_NDX;

***/


define DEFAULT_TABLESPACE_TABLE = STC_DATA;
define DEFAULT_TABLESPACE_INDEX = STC_DATA;
define PE_TABLESPACE_TABLE = STC_DATA;
define PE_TABLESPACE_INDEX = STC_DATA;

