alter table STC_OMH_IUD_LOG add source_username VARCHAR2(2000);
alter table STC_OMH_IUD_LOG add source_hostname VARCHAR2(2000);


CREATE OR REPLACE TRIGGER STC_OMH_IUD_DELETE_TRIGGER AFTER
    DELETE
    ON STC_ORDER_MESSAGE_HOME
    FOR EACH ROW
    BEGIN
      INSERT INTO STC_OMH_IUD_LOG(CWORDERID, ORDER_ACTION, ORDERNUMBER, PARENTORDERNUMBER, USERNAME, SOURCE_USERNAME, SOURCE_HOSTNAME)
        VALUES (:OLD.CWORDERID, 'D', :OLD.ORDERNUMBER, :OLD.PARENTORDERNUMBER, user, SYS_CONTEXT('USERENV','OS_USER'), SYS_CONTEXT('USERENV','HOST'));
    END;
/


CREATE OR REPLACE TRIGGER STC_OMH_IUD_INSERT_TRIGGER AFTER
    INSERT
    ON STC_ORDER_MESSAGE_HOME
    FOR EACH ROW
    BEGIN
      INSERT INTO STC_OMH_IUD_LOG(CWORDERID, ORDER_ACTION, ORDERNUMBER, PARENTORDERNUMBER, USERNAME, SOURCE_USERNAME, SOURCE_HOSTNAME)
        VALUES (:OLD.CWORDERID, 'I', :NEW.ORDERNUMBER, :NEW.PARENTORDERNUMBER, user, SYS_CONTEXT('USERENV','OS_USER'), SYS_CONTEXT('USERENV','HOST'));
    END;
/


CREATE OR REPLACE TRIGGER STC_OMH_IUD_UPDATE_TRIGGER AFTER
    UPDATE
    OF ORDERNUMBER, PARENTORDERNUMBER ON STC_ORDER_MESSAGE_HOME
    FOR EACH ROW
    BEGIN
      INSERT INTO STC_OMH_IUD_LOG(CWORDERID, ORDER_ACTION, ORDERNUMBER, OLD_ORDERNUMBER, PARENTORDERNUMBER, OLD_PARENTORDERNUMBER, USERNAME, SOURCE_USERNAME, SOURCE_HOSTNAME)
        VALUES (:OLD.CWORDERID, 'U', :NEW.ORDERNUMBER, :OLD.ORDERNUMBER, :NEW.PARENTORDERNUMBER, :OLD.PARENTORDERNUMBER, user, SYS_CONTEXT('USERENV','OS_USER'), SYS_CONTEXT('USERENV','HOST'));
    END;
/