define DEFAULT_TABLESPACE_TABLE = CWH;
define DEFAULT_TABLESPACE_INDEX = CWH_NDX;

create table STC_NAMEVALUE_REPLACEMENT(
	CWDOCID varchar2(16) NOT NULL,
	NAME varchar2(100),
	RECEIVEDVALUE varchar2(4000),
	REPLACEDWITHVALUE varchar2(4000)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;


alter table STC_NAMEVALUE_REPLACEMENT 
add constraint PK_STC_NAMEVALUE_REPLACEMENT primary key (CWDOCID)
using index 
tablespace &DEFAULT_TABLESPACE_INDEX;

alter table STC_NAMEVALUE_REPLACEMENT 
add constraint UK_STC_NV_REPLACEMENT unique (NAME, RECEIVEDVALUE)
using index
tablespace &DEFAULT_TABLESPACE_INDEX;

insert into STC_NAMEVALUE_REPLACEMENT VALUES ('1', 'BILL LANGUAGE', 'A', '1');
insert into STC_NAMEVALUE_REPLACEMENT VALUES ('2', 'BILL LANGUAGE', 'E', '0');
commit;