alter table CWORDERITEMS drop constraint CWORDERITEMS_ITEMID;
drop index CWORDERITEMS_ITEMID;

alter table CWORDERITEMS add constraint CWORDERITEMS_ITEMID primary key (ITEMID)
using index GLOBAL PARTITION BY HASH (ITEMID)
     (PARTITION p1  TABLESPACE CWH_NDX,
      PARTITION p2  TABLESPACE CWH_NDX,
      PARTITION p3  TABLESPACE CWH_NDX,
      PARTITION p4  TABLESPACE CWH_NDX,
      PARTITION p5  TABLESPACE CWH_NDX,
      PARTITION p6  TABLESPACE CWH_NDX,
      PARTITION p7  TABLESPACE CWH_NDX,
      PARTITION p8  TABLESPACE CWH_NDX);

drop index CWORDERITEMS_ORDID /* CWORDERITEMS(TOPORDERID) */ ;

CREATE INDEX CWORDERITEMS_ORDID ON CWORDERITEMS (TOPORDERID) COMPRESS 1 GLOBAL PARTITION BY HASH (TOPORDERID)
     (PARTITION p1  TABLESPACE CWH_NDX,
      PARTITION p2  TABLESPACE CWH_NDX,
      PARTITION p3  TABLESPACE CWH_NDX,
      PARTITION p4  TABLESPACE CWH_NDX,
      PARTITION p5  TABLESPACE CWH_NDX,
      PARTITION p6  TABLESPACE CWH_NDX,
      PARTITION p7  TABLESPACE CWH_NDX,
      PARTITION p8  TABLESPACE CWH_NDX);