alter index CWFELOG0 /* CWPROCESSEVENTLOG(EVENT_ID) */ rebuild compress 1;

alter table CWPROCESSEVENTLOG drop constraint CWPK_PROCESSEVENTLOG;
drop index CWPK_PROCESSEVENTLOG /* CWPROCESSEVENTLOG(EVENT_ID) */ ;

alter table CWPROCESSEVENTLOG add constraint CWPK_PROCESSEVENTLOG primary key (EVENT_ID)
using index GLOBAL PARTITION BY HASH (EVENT_ID)
     (PARTITION p1   TABLESPACE CWH_NDX,
      PARTITION p2   TABLESPACE CWH_NDX,
      PARTITION p3   TABLESPACE CWH_NDX,
      PARTITION p4   TABLESPACE CWH_NDX,
      PARTITION p5   TABLESPACE CWH_NDX,
      PARTITION p6   TABLESPACE CWH_NDX,
      PARTITION p7   TABLESPACE CWH_NDX,
      PARTITION p8   TABLESPACE CWH_NDX,
      PARTITION p9   TABLESPACE CWH_NDX,
      PARTITION p10  TABLESPACE CWH_NDX,
      PARTITION p11  TABLESPACE CWH_NDX,
      PARTITION p12  TABLESPACE CWH_NDX);
