CREATE OR REPLACE
PROCEDURE DELETE_PROCESS_ACTIVE(pid in NUMBER, batchSize in NUMBER, tabNum in NUMBER, activityFlag in NUMBER)
AS
  ret NUMBER;
BEGIN

    IF (pid = 0) THEN
       CASE tabNum
          WHEN  0 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE0  cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN  1 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE1  cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN  2 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE2  cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN  3 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE3  cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN  4 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE4  cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN  5 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE5  cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN  6 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE6  cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN  7 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE7  cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN  8 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE8  cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN  9 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE9  cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN 10 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE10 cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN 11 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE11 cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN 12 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE12 cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN 13 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE13 cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN 14 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE14 cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN 15 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE15 cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN 16 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE16 cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN 17 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE17 cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN 18 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE18 cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          WHEN 19 THEN INSERT INTO CWPIDS(PROCESS_ID) SELECT process_id FROM CWPROCESS_ACTIVE19 cwp WHERE status IN (3,6) AND ROWNUM < batchSize;
          ELSE execute immediate 'INSERT INTO CWPIDS' || ' SELECT /*+ PARALLEL(cwp,4) */ process_id FROM CWPROCESS_ACTIVE' || tabNum || ' cwp WHERE status IN (3,6) AND ROWNUM < ' || batchSize;
       END CASE;
    ELSE
        INSERT INTO CWPIDS(PROCESS_ID) VALUES(pid);
    END IF;
    SELECT COUNT(*) INTO ret FROM cwpids;
    IF ret <> 0 THEN
      IF activityFlag = 1 THEN
        CASE tabNum
           WHEN  0 THEN INSERT INTO CWPACTIVITYARC0  cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY0  cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  1 THEN INSERT INTO CWPACTIVITYARC1  cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY1  cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  2 THEN INSERT INTO CWPACTIVITYARC2  cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY2  cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  3 THEN INSERT INTO CWPACTIVITYARC3  cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY3  cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  4 THEN INSERT INTO CWPACTIVITYARC4  cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY4  cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  5 THEN INSERT INTO CWPACTIVITYARC5  cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY5  cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  6 THEN INSERT INTO CWPACTIVITYARC6  cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY6  cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  7 THEN INSERT INTO CWPACTIVITYARC7  cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY7  cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  8 THEN INSERT INTO CWPACTIVITYARC8  cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY8  cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  9 THEN INSERT INTO CWPACTIVITYARC9  cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY9  cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 10 THEN INSERT INTO CWPACTIVITYARC10 cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY10 cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 11 THEN INSERT INTO CWPACTIVITYARC11 cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY11 cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 12 THEN INSERT INTO CWPACTIVITYARC12 cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY12 cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 13 THEN INSERT INTO CWPACTIVITYARC13 cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY13 cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 14 THEN INSERT INTO CWPACTIVITYARC14 cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY14 cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 15 THEN INSERT INTO CWPACTIVITYARC15 cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY15 cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 16 THEN INSERT INTO CWPACTIVITYARC16 cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY16 cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 17 THEN INSERT INTO CWPACTIVITYARC17 cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY17 cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 18 THEN INSERT INTO CWPACTIVITYARC18 cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY18 cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 19 THEN INSERT INTO CWPACTIVITYARC19 cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME) SELECT PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY19 cwa WHERE PROCESS_ID IN (select process_id FROM cwpids);
           ELSE EXECUTE IMMEDIATE
          'INSERT /*+ PARALLEL(cwar,4) */ INTO CWPACTIVITYARC' || tabNum || ' cwar (PROCESS_ID,ACTIVITY_INDEX,START_TIME,COMPLETION_TIME)' ||
          '  SELECT /*+ PARALLEL(cwa,4) */ PROCESS_ID,ACTIVITY_INDEX,NVL(START_TIME,sysdate),COMPLETION_TIME FROM CWPACTIVITY' || tabNum || ' cwa WHERE PROCESS_ID IN (select process_id FROM cwpids)';
        END CASE;
        CASE tabNum
           WHEN  0 THEN DELETE FROM CWPACTIVITY0  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  1 THEN DELETE FROM CWPACTIVITY1  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  2 THEN DELETE FROM CWPACTIVITY2  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  3 THEN DELETE FROM CWPACTIVITY3  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  4 THEN DELETE FROM CWPACTIVITY4  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  5 THEN DELETE FROM CWPACTIVITY5  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  6 THEN DELETE FROM CWPACTIVITY6  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  7 THEN DELETE FROM CWPACTIVITY7  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  8 THEN DELETE FROM CWPACTIVITY8  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN  9 THEN DELETE FROM CWPACTIVITY9  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 10 THEN DELETE FROM CWPACTIVITY10 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 11 THEN DELETE FROM CWPACTIVITY11 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 12 THEN DELETE FROM CWPACTIVITY12 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 13 THEN DELETE FROM CWPACTIVITY13 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 14 THEN DELETE FROM CWPACTIVITY14 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 15 THEN DELETE FROM CWPACTIVITY15 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 16 THEN DELETE FROM CWPACTIVITY16 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 17 THEN DELETE FROM CWPACTIVITY17 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 18 THEN DELETE FROM CWPACTIVITY18 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           WHEN 19 THEN DELETE FROM CWPACTIVITY19 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
           ELSE EXECUTE IMMEDIATE 'DELETE /*+ FULL(t) PARALLEL(t,8) */ FROM CWPACTIVITY' || tabNum || ' t WHERE PROCESS_ID IN (select process_id FROM cwpids)';
        END CASE;
      END IF;
      CASE tabNum
         WHEN  0 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE0  cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  1 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE1  cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  2 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE2  cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  3 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE3  cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  4 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE4  cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  5 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE5  cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  6 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE6  cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  7 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE7  cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  8 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE8  cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  9 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE9  cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 10 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE10 cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 11 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE11 cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 12 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE12 cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 13 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE13 cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 14 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE14 cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 15 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE15 cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 16 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE16 cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 17 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE17 cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 18 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE18 cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 19 THEN INSERT INTO CWPROCESS_COMPLETED cwpc SELECT * FROM CWPROCESS_ACTIVE19 cwp WHERE PROCESS_ID IN (select process_id FROM cwpids);
         ELSE EXECUTE IMMEDIATE 'INSERT /*+ PARALLEL(cwpc,4) */ INTO CWPROCESS_COMPLETED cwpc SELECT /*+ PARALLEL(cwp,4) */ * FROM CWPROCESS_ACTIVE' || tabNum ||
          ' cwp WHERE PROCESS_ID IN (select process_id FROM cwpids)';
      END CASE;
      CASE tabNum
         WHEN  0 THEN DELETE FROM CWPROCESS_ACTIVE0  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  1 THEN DELETE FROM CWPROCESS_ACTIVE1  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  2 THEN DELETE FROM CWPROCESS_ACTIVE2  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  3 THEN DELETE FROM CWPROCESS_ACTIVE3  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  4 THEN DELETE FROM CWPROCESS_ACTIVE4  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  5 THEN DELETE FROM CWPROCESS_ACTIVE5  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  6 THEN DELETE FROM CWPROCESS_ACTIVE6  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  7 THEN DELETE FROM CWPROCESS_ACTIVE7  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  8 THEN DELETE FROM CWPROCESS_ACTIVE8  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN  9 THEN DELETE FROM CWPROCESS_ACTIVE9  t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 10 THEN DELETE FROM CWPROCESS_ACTIVE10 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 11 THEN DELETE FROM CWPROCESS_ACTIVE11 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 12 THEN DELETE FROM CWPROCESS_ACTIVE12 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 13 THEN DELETE FROM CWPROCESS_ACTIVE13 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 14 THEN DELETE FROM CWPROCESS_ACTIVE14 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 15 THEN DELETE FROM CWPROCESS_ACTIVE15 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 16 THEN DELETE FROM CWPROCESS_ACTIVE16 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 17 THEN DELETE FROM CWPROCESS_ACTIVE17 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 18 THEN DELETE FROM CWPROCESS_ACTIVE18 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         WHEN 19 THEN DELETE FROM CWPROCESS_ACTIVE19 t WHERE PROCESS_ID IN (select process_id FROM cwpids);
         ELSE EXECUTE IMMEDIATE 'DELETE /*+ FULL(t) PARALLEL(t,8) */ FROM CWPROCESS_ACTIVE' || tabNum || ' t WHERE PROCESS_ID IN (select process_id FROM cwpids)';
      END CASE;
    END IF;
END;
/