insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, TASK_OPERATION, CRM_B2B, CRM_BAU) select max(to_number(CWDOCID)) + 1, 0, 'SIP_SN', 'FIX REJECT-SALES', 1, 0 from STC_SKIP_WOSU;
insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, TASK_OPERATION, CRM_B2B, CRM_BAU) select max(to_number(CWDOCID)) + 1, 0, 'SIP_UAN', 'FIX REJECT-SALES', 1, 0 from STC_SKIP_WOSU;
insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, TASK_OPERATION, CRM_B2B, CRM_BAU) select max(to_number(CWDOCID)) + 1, 0, 'SIP_TF', 'FIX REJECT-SALES', 1, 0 from STC_SKIP_WOSU;
insert into STC_SKIP_WOSU(CWDOCID, IS_FLAT, SERVICETYPE, TASK_OPERATION, CRM_B2B, CRM_BAU) select max(to_number(CWDOCID)) + 1, 0, 'DID_SIP', 'FIX REJECT-SALES', 1, 0 from STC_SKIP_WOSU;

commit;
