insert into STC_ORDERHEADER_VALIDMAP_NOCHG (ORDERTYPE, CUSTOMERIDNUMBER, ACCOUNTNUMBER, CUSTOMERTYPE, CUSTOMERIDTYPE, CUSTOMERCONTACT, CUSTOMERCONTACTNAME, CUSTOMERNAME, CUSTOMERNUMBER, CREATEDBYNAME, CREATEDBYCONTACTNAME, SERVICEDATE, PRIORITY, REMARKS, REFERENCETELNUMBER, VERSION, CUSTOMERSEGMENTATION, FEASIBILITYFOR, RESERVATION, RESERVATIONNUMBER, ICMSSALESORDERNUMBER)
values ('T', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

insert into STC_LINEITEM_VALIDMAP_NOCHG (ORDERTYPE, LINEITEMIDENTIFIER, LINEITEMTYPE, SERVICETYPE, SERVICENUMBER, OLDSERVICENUMBER, PRODUCTTYPE, REMARKS, REFERENCETELNUMBER, SERVICEDESCRIPTION, BANDWIDTH, ACCOUNTNUMBER, OLDACCOUNTNUMBER, PROJECTID, LOCATIONACITY, LOCATIONACCLICODE, LOCATIONAACCESSCIRCUIT, LOCATIONAJVCODE, LOCATIONAEXCHANGESWITCHCODE, LOCATIONAACCESSTYPE, LOCATIONAPLATEID, LOCATIONAOLDPLATEID, LOCATIONACONTACTADDRESS, LOCATIONACONTACTNAME, LOCATIONACONTACTTEL, LOCATIONACONTACTEMAIL, LOCATIONAUNITNUMBER, LOCATIONAINTERFACE, LOCATIONAREMARKS, LOCATIONBCITY, LOCATIONBCCLICODE, LOCATIONBACCESSCIRCUIT, LOCATIONBJVCODE, LOCATIONBEXCHANGESWITCHCODE, LOCATIONBACCESSTYPE, LOCATIONBPLATEID, LOCATIONBOLDPLATEID, LOCATIONBCONTACTADDRESS, LOCATIONBCONTACTNAME, LOCATIONBCONTACTTEL, LOCATIONBCONTACTEMAIL, LOCATIONBUNITNUMBER, LOCATIONBINTERFACE, LOCATIONBREMARKS, TBPORTNUMBER, WIRES, SERVICEDATE, CREATIONDATE, DEPENDENCIES)
values ('T', 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1);


commit;
