-- ACTIVATE NSM
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('customerIdNumber', 'OH', 'accountId', 'RH', 'NSM', 'ACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'additionalKey', 'RH', 'NSM', 'ACTIVATE', 'DEFAULT');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('businessUnit', 'OH', 'businessUnit', 'RH', 'NSM', 'ACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'channel', 'RH', 'NSM', 'ACTIVATE', 'Zira CRM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('createdBy', 'OH', 'agentUserName', 'RH', 'NSM', 'ACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'orderNumber', 'RH', 'NSM', 'ACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderType', 'OH', 'orderType', 'RH', 'NSM', 'ACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'serviceCategory', 'RH', 'NSM', 'ACTIVATE', 'NSM_WBU');

insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'action', 'LI', 'NSM', 'ACTIVATE', 'ACTIVATE');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'associationFlag', 'LI', 'NSM', 'ACTIVATE', 'N');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'connectionType', 'LI', 'NSM', 'ACTIVATE', 'POSTPAID');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'inactivateSIM', 'LI', 'NSM', 'ACTIVATE', 'N');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'joinExistFlag', 'LI', 'NSM', 'ACTIVATE', 'Y');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('PrimaryPhoneNumber', 'NV', 'number', 'LI', 'NSM', 'ACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderType', 'OH', 'orderType', 'LI', 'NSM', 'ACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'phoneNumExists', 'LI', 'NSM', 'ACTIVATE', 'Y');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'reserveNumFlag', 'LI', 'NSM', 'ACTIVATE', 'N');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'simNumExists', 'LI', 'NSM', 'ACTIVATE', 'Y');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('SIM Number', 'NV', 'simNumber', 'LI', 'NSM', 'ACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'teleCode', 'LI', 'NSM', 'ACTIVATE', 'GDATA');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('Provider', 'NV', 'toServiceProvider', 'LI', 'NSM', 'ACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'type', 'LI', 'NSM', 'ACTIVATE', 'NORMAL');

-- DEACTIVATE NSM
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('customerIdNumber', 'OH', 'accountId', 'RH', 'NSM', 'DEACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'additionalKey', 'RH', 'NSM', 'DEACTIVATE', 'DEFAULT');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('businessUnit', 'OH', 'businessUnit', 'RH', 'NSM', 'DEACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'channel', 'RH', 'NSM', 'DEACTIVATE', 'Zira CRM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('createdBy', 'OH', 'agentUserName', 'RH', 'NSM', 'DEACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'orderNumber', 'RH', 'NSM', 'DEACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderType', 'OH', 'orderType', 'RH', 'NSM', 'DEACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'serviceCategory', 'RH', 'NSM', 'DEACTIVATE', 'NSM_WBU');

insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'action', 'LI', 'NSM', 'DEACTIVATE', 'DISCONNECT');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'associationFlag', 'LI', 'NSM', 'DEACTIVATE', 'Y');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'connectionType', 'LI', 'NSM', 'DEACTIVATE', 'POSTPAID');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'disconnectedBY', 'LI', 'NSM', 'DEACTIVATE', 'CustomerInitiated');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'inactivateSIM', 'LI', 'NSM', 'DEACTIVATE', 'N');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'joinExistFlag', 'LI', 'NSM', 'DEACTIVATE', 'Y');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('PrimaryPhoneNumber', 'NV', 'number', 'LI', 'NSM', 'DEACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('OldSIMNumber', 'NV', 'oldSIMNumber', 'LI', 'NSM', 'DEACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderType', 'OH', 'orderType', 'LI', 'NSM', 'DEACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'phoneNumExists', 'LI', 'NSM', 'DEACTIVATE', 'Y');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'reserveNumFlag', 'LI', 'NSM', 'DEACTIVATE', 'N');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'simNumExists', 'LI', 'NSM', 'DEACTIVATE', 'Y');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('SIM Number', 'NV', 'simNumber', 'LI', 'NSM', 'DEACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'teleCode', 'LI', 'NSM', 'DEACTIVATE', 'GDATA');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('Provider', 'NV', 'toServiceProvider', 'LI', 'NSM', 'DEACTIVATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'type', 'LI', 'NSM', 'DEACTIVATE', 'NORMAL');

-- VALIDATE NSM
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('customerIdNumber', 'OH', 'accountId', 'RH', 'NSM', 'VALIDATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'additionalKey', 'RH', 'NSM', 'VALIDATE', 'Validate');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('businessUnit', 'OH', 'businessUnit', 'RH', 'NSM', 'VALIDATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'channel', 'RH', 'NSM', 'VALIDATE', 'Zira CRM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('createdBy', 'OH', 'agentUserName', 'RH', 'NSM', 'VALIDATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'orderNumber', 'RH', 'NSM', 'VALIDATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderType', 'OH', 'orderType', 'RH', 'NSM', 'VALIDATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'serviceCategory', 'RH', 'NSM', 'VALIDATE', 'NSM_WBU');

insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('PrimaryPhoneNumber', 'NV', 'number', 'LI', 'NSM', 'VALIDATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderType', 'OH', 'orderType', 'LI', 'NSM', 'VALIDATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('Provider', 'NV', 'serviceProvider', 'LI', 'NSM', 'VALIDATE', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('SIM Number', 'NV', 'simNumber', 'LI', 'NSM', 'VALIDATE', null);

-- CHANGE_SIM NSM
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('customerIdNumber', 'OH', 'accountId', 'RH', 'NSM', 'CHANGE_SIM', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'additionalKey', 'RH', 'NSM', 'CHANGE_SIM', 'DEFAULT');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('businessUnit', 'OH', 'businessUnit', 'RH', 'NSM', 'CHANGE_SIM', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'channel', 'RH', 'NSM', 'CHANGE_SIM', 'Zira CRM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('createdBy', 'OH', 'agentUserName', 'RH', 'NSM', 'CHANGE_SIM', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'orderNumber', 'RH', 'NSM', 'CHANGE_SIM', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'orderSubType', 'RH', 'NSM', 'CHANGE_SIM', 'CHANGE_SIM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderType', 'OH', 'orderType', 'RH', 'NSM', 'CHANGE_SIM', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'serviceCategory', 'RH', 'NSM', 'CHANGE_SIM', 'NSM_WBU');

insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('OldPhoneNumber', 'NV', 'oldNumber', 'LI', 'NSM', 'CHANGE_SIM', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('OldSIMNumber', 'NV', 'oldSIMNumber', 'LI', 'NSM', 'CHANGE_SIM', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'orderSubType', 'LI', 'NSM', 'CHANGE_SIM', 'CHANGE_SIM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderType', 'OH', 'orderType', 'LI', 'NSM', 'CHANGE_SIM', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('Provider', 'NV', 'serviceProvider', 'LI', 'NSM', 'CHANGE_SIM', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('SIM Number', 'NV', 'simNumber', 'LI', 'NSM', 'CHANGE_SIM', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'teleCode', 'LI', 'NSM', 'CHANGE_SIM', 'GDATA');


commit;