/***

define DEFAULT_TABLESPACE_TABLE = CWW;
define DEFAULT_TABLESPACE_INDEX = CWW_NDX;

***/


define DEFAULT_TABLESPACE_TABLE = STC_DATA;
define DEFAULT_TABLESPACE_INDEX = STC_DATA;

CREATE INDEX stcw_gran_evt_stor_procid ON stcw_granite_event_storage(processid)
  TABLESPACE &DEFAULT_TABLESPACE_INDEX;
