-- ALL
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'serviceType', 'RH', 'P_A', 'ALL', 'LTE');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'trackingId', 'RH', 'P_A', 'ALL', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'processingMode', 'RH', 'P_A', 'ALL', 'SYNC');

-- INSTALL
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'NE_TYPE', 'NV', 'P_A', 'INSTALL', 'BST');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'REQ_TYPE', 'NV', 'P_A', 'INSTALL', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'INSTALL', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'INSTALL', 'CRE_SUBS_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'INSTALL', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'INSTALL', 'UNKNOWN'); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('PrimaryPhoneNumber', 'NV', 'MSISDN1', 'NV', 'P_A', 'INSTALL', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('IMSI Number', 'NV', 'IMSI1', 'NV', 'P_A', 'INSTALL', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('Speed Profile', 'NV', 'SERVICEID', 'NV', 'P_A', 'INSTALL', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'SUBS_PROFILE', 'NV', 'P_A', 'INSTALL', '119');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'APN_ID', 'NV', 'P_A', 'INSTALL', '103');

-- CHANGE PROFILE
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'NE_TYPE', 'NV', 'P_A', 'CHANGE_PRFL', 'BST');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'REQ_TYPE', 'NV', 'P_A', 'CHANGE_PRFL', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'CHANGE_PRFL', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'CHANGE_PRFL', 'MOD_SUBS_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'CHANGE_PRFL', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'CHANGE_PRFL', 'UNKNOWN'); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('PrimaryPhoneNumber', 'NV', 'MSISDN1', 'NV', 'P_A', 'CHANGE_PRFL', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('IMSI Number', 'NV', 'IMSI1', 'NV', 'P_A', 'CHANGE_PRFL', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('Old Speed Profile', 'NV', 'SERVICEID', 'NV', 'P_A', 'CHANGE_PRFL', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('Speed Profile', 'NV', 'NEW_SERVICEID', 'NV', 'P_A', 'CHANGE_PRFL', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'APN_ID', 'NV', 'P_A', 'CHANGE_PRFL', '103');

-- Rollback for CHANGE PROFILE
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'NE_TYPE', 'NV', 'P_A', 'CHANGE_PRFL_R', 'BST');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'REQ_TYPE', 'NV', 'P_A', 'CHANGE_PRFL_R', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'CHANGE_PRFL_R', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'CHANGE_PRFL_R', 'MOD_SUBS_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'CHANGE_PRFL_R', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'CHANGE_PRFL_R', 'UNKNOWN'); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('PrimaryPhoneNumber', 'NV', 'MSISDN1', 'NV', 'P_A', 'CHANGE_PRFL_R', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('IMSI Number', 'NV', 'IMSI1', 'NV', 'P_A', 'CHANGE_PRFL_R', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('Speed Profile', 'NV', 'SERVICEID', 'NV', 'P_A', 'CHANGE_PRFL_R', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('Old Speed Profile', 'NV', 'NEW_SERVICEID', 'NV', 'P_A', 'CHANGE_PRFL_R', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'APN_ID', 'NV', 'P_A', 'CHANGE_PRFL_R', '103');

-- SUSPEND
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'NE_TYPE', 'NV', 'P_A', 'SUSPEND', 'BST');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'REQ_TYPE', 'NV', 'P_A', 'SUSPEND', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'SUSPEND', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'SUSPEND', 'SUSPEND_SUBS_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'SUSPEND', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'SUSPEND', 'UNKNOWN'); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('PrimaryPhoneNumber', 'NV', 'MSISDN1', 'NV', 'P_A', 'SUSPEND', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('IMSI Number', 'NV', 'IMSI1', 'NV', 'P_A', 'SUSPEND', null);

-- RESUME
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'NE_TYPE', 'NV', 'P_A', 'RESUME', 'BST');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'REQ_TYPE', 'NV', 'P_A', 'RESUME', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'RESUME', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'RESUME', 'RESUME_SUBS_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'RESUME', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'RESUME', 'UNKNOWN'); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('PrimaryPhoneNumber', 'NV', 'MSISDN1', 'NV', 'P_A', 'RESUME', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('IMSI Number', 'NV', 'IMSI1', 'NV', 'P_A', 'RESUME', null);

-- CHANGE SIM
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'NE_TYPE', 'NV', 'P_A', 'CHANGE_SIM', 'BST');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'REQ_TYPE', 'NV', 'P_A', 'CHANGE_SIM', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'CHANGE_SIM', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'CHANGE_SIM', 'CHANGE_SIM_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'CHANGE_SIM', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'CHANGE_SIM', 'UNKNOWN'); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('PrimaryPhoneNumber', 'NV', 'MSISDN1', 'NV', 'P_A', 'CHANGE_SIM', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('Old IMSI Number', 'NV', 'IMSI1', 'NV', 'P_A', 'CHANGE_SIM', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('IMSI Number', 'NV', 'NEW_IMSI1', 'NV', 'P_A', 'CHANGE_SIM', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('Speed Profile', 'NV', 'SERVICEID', 'NV', 'P_A', 'CHANGE_SIM', null); --?????

-- Rollback for CHANGE SIM
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'NE_TYPE', 'NV', 'P_A', 'CHANGE_SIM_R', 'BST');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'REQ_TYPE', 'NV', 'P_A', 'CHANGE_SIM_R', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'CHANGE_SIM_R', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'CHANGE_SIM_R', 'CHANGE_SIM_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'CHANGE_SIM_R', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'CHANGE_SIM_R', 'UNKNOWN'); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('PrimaryPhoneNumber', 'NV', 'MSISDN1', 'NV', 'P_A', 'CHANGE_SIM_R', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('IMSI Number', 'NV', 'IMSI1', 'NV', 'P_A', 'CHANGE_SIM_R', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('Old IMSI Number', 'NV', 'NEW_IMSI1', 'NV', 'P_A', 'CHANGE_SIM_R', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('Speed Profile', 'NV', 'SERVICEID', 'NV', 'P_A', 'CHANGE_SIM_R', null); --?????

-- DISCONNECT
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'NE_TYPE', 'NV', 'P_A', 'DISCONNECT', 'BST');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'REQ_TYPE', 'NV', 'P_A', 'DISCONNECT', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'DISCONNECT', null); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'DISCONNECT', 'DEL_SUBS_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'DISCONNECT', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'DISCONNECT', 'UNKNOWN'); --?????
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('PrimaryPhoneNumber', 'NV', 'MSISDN1', 'NV', 'P_A', 'DISCONNECT', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('IMSI Number', 'NV', 'IMSI1', 'NV', 'P_A', 'DISCONNECT', null);

commit;
