-- ALL
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'serviceType', 'RH', 'P_A', 'ALL', 'LTE');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values ('orderNumber', 'OH', 'trackingId', 'RH', 'P_A', 'ALL', null);
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values (null, null, 'processingMode', 'RH', 'P_A', 'ALL', 'SYNC');

-- INSTALL
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_APN_ID', 'NV', 'P_A', 'INSTALL', '103');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('IMSI Number', 'NV', 'SO1_IMSI1', 'NV', 'P_A', 'INSTALL', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('PrimaryPhoneNumber', 'NV', 'SO1_MSISDN1', 'NV', 'P_A', 'INSTALL', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'NE_TYPE', 'NV', 'P_A', 'INSTALL', 'ILGSM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'INSTALL', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'REQ_TYPE', 'NV', 'P_A', 'INSTALL', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'INSTALL', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'INSTALL', 'UNKNOWN');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('Speed Profile', 'NV', 'SO1_SERVICEID', 'NV', 'P_A', 'INSTALL', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'INSTALL', 'CRE_SUBS_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_SUBS_PROFILE', 'NV', 'P_A', 'INSTALL', '119');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERTYPE', 'NV', 'P_A', 'INSTALL', 'New');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERSUBTYPE', 'NV', 'P_A', 'INSTALL', 'DEFAULT');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_ACTIONCODE', 'NV', 'P_A', 'INSTALL', 'New');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_TECHNICALPRODUCT', 'NV', 'P_A', 'INSTALL', 'TP_ATHEEB');

-- CHANGE PROFILE
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_APN_ID', 'NV', 'P_A', 'CHANGE_PRFL', '103');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('IMSI Number', 'NV', 'SO1_IMSI1', 'NV', 'P_A', 'CHANGE_PRFL', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('PrimaryPhoneNumber', 'NV', 'SO1_MSISDN1', 'NV', 'P_A', 'CHANGE_PRFL', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('Speed Profile', 'NV', 'SO1_NEW_SERVICEID', 'NV', 'P_A', 'CHANGE_PRFL', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'NE_TYPE', 'NV', 'P_A', 'CHANGE_PRFL', 'ILGSM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'CHANGE_PRFL', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'REQ_TYPE', 'NV', 'P_A', 'CHANGE_PRFL', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'CHANGE_PRFL', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'CHANGE_PRFL', 'UNKNOWN');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('Old Speed Profile', 'NV', 'SO1_SERVICEID', 'NV', 'P_A', 'CHANGE_PRFL', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'CHANGE_PRFL', 'MOD_SUBS_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERTYPE', 'NV', 'P_A', 'CHANGE_PRFL', 'Modify');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERSUBTYPE', 'NV', 'P_A', 'CHANGE_PRFL', 'ChangeService');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_ACTIONCODE', 'NV', 'P_A', 'CHANGE_PRFL', 'Modified');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_TECHNICALPRODUCT', 'NV', 'P_A', 'CHANGE_PRFL', 'TP_ATHEEB');

-- Rollback for CHANGE PROFILE
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_APN_ID', 'NV', 'P_A', 'CHANGE_PRFL_R', '103');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('IMSI Number', 'NV', 'SO1_IMSI1', 'NV', 'P_A', 'CHANGE_PRFL_R', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('PrimaryPhoneNumber', 'NV', 'SO1_MSISDN1', 'NV', 'P_A', 'CHANGE_PRFL_R', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('Old Speed Profile', 'NV', 'SO1_NEW_SERVICEID', 'NV', 'P_A', 'CHANGE_PRFL_R', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'NE_TYPE', 'NV', 'P_A', 'CHANGE_PRFL_R', 'ILGSM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'CHANGE_PRFL_R', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'REQ_TYPE', 'NV', 'P_A', 'CHANGE_PRFL_R', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'CHANGE_PRFL_R', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'CHANGE_PRFL_R', 'UNKNOWN');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('Speed Profile', 'NV', 'SO1_SERVICEID', 'NV', 'P_A', 'CHANGE_PRFL_R', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'CHANGE_PRFL_R', 'MOD_SUBS_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERTYPE', 'NV', 'P_A', 'CHANGE_PRFL_R', 'Modify');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERSUBTYPE', 'NV', 'P_A', 'CHANGE_PRFL_R', 'ChangeService');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_ACTIONCODE', 'NV', 'P_A', 'CHANGE_PRFL_R', 'Modified');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_TECHNICALPRODUCT', 'NV', 'P_A', 'CHANGE_PRFL_R', 'TP_ATHEEB');

-- SUSPEND
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('IMSI Number', 'NV', 'SO1_IMSI1', 'NV', 'P_A', 'SUSPEND', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('PrimaryPhoneNumber', 'NV', 'SO1_MSISDN1', 'NV', 'P_A', 'SUSPEND', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'NE_TYPE', 'NV', 'P_A', 'SUSPEND', 'ILGSM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'SUSPEND', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'REQ_TYPE', 'NV', 'P_A', 'SUSPEND', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'SUSPEND', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'SUSPEND', 'UNKNOWN');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'SUSPEND', 'SUSPEND_SUBS_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERTYPE', 'NV', 'P_A', 'SUSPEND', 'DEFAULT');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERSUBTYPE', 'NV', 'P_A', 'SUSPEND', 'DEFAULT');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_ACTIONCODE', 'NV', 'P_A', 'SUSPEND', 'Suspend');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_TECHNICALPRODUCT', 'NV', 'P_A', 'SUSPEND', 'TP_ATHEEB');

-- RESUME
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('IMSI Number', 'NV', 'SO1_IMSI1', 'NV', 'P_A', 'RESUME', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('PrimaryPhoneNumber', 'NV', 'SO1_MSISDN1', 'NV', 'P_A', 'RESUME', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'NE_TYPE', 'NV', 'P_A', 'RESUME', 'ILGSM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'RESUME', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'REQ_TYPE', 'NV', 'P_A', 'RESUME', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'RESUME', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'RESUME', 'UNKNOWN');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'RESUME', 'RESUME_SUBS_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERTYPE', 'NV', 'P_A', 'RESUME', 'DEFAULT');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERSUBTYPE', 'NV', 'P_A', 'RESUME', 'DEFAULT');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_ACTIONCODE', 'NV', 'P_A', 'RESUME', 'Resume');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_TECHNICALPRODUCT', 'NV', 'P_A', 'RESUME', 'TP_ATHEEB');

-- CHANGE SIM
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('Old IMSI Number', 'NV', 'SO1_IMSI1', 'NV', 'P_A', 'CHANGE_SIM', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('PrimaryPhoneNumber', 'NV', 'SO1_MSISDN1', 'NV', 'P_A', 'CHANGE_SIM', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('IMSI Number', 'NV', 'SO1_NEW_IMSI1', 'NV', 'P_A', 'CHANGE_SIM', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'NE_TYPE', 'NV', 'P_A', 'CHANGE_SIM', 'ILGSM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'CHANGE_SIM', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'REQ_TYPE', 'NV', 'P_A', 'CHANGE_SIM', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'CHANGE_SIM', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'CHANGE_SIM', 'UNKNOWN');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('Speed Profile', 'NV', 'SO1_SERVICEID', 'NV', 'P_A', 'CHANGE_SIM', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'CHANGE_SIM', 'CHANGE_SIM_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERTYPE', 'NV', 'P_A', 'CHANGE_SIM', 'Change SIM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERSUBTYPE', 'NV', 'P_A', 'CHANGE_SIM', 'DEFAULT');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_ACTIONCODE', 'NV', 'P_A', 'CHANGE_SIM', 'Change SIM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_TECHNICALPRODUCT', 'NV', 'P_A', 'CHANGE_SIM', 'TP_ATHEEB');

-- Rollback for CHANGE SIM
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('IMSI Number', 'NV', 'SO1_IMSI1', 'NV', 'P_A', 'CHANGE_SIM_R', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('PrimaryPhoneNumber', 'NV', 'SO1_MSISDN1', 'NV', 'P_A', 'CHANGE_SIM_R', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('Old IMSI Number', 'NV', 'SO1_NEW_IMSI1', 'NV', 'P_A', 'CHANGE_SIM_R', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'NE_TYPE', 'NV', 'P_A', 'CHANGE_SIM_R', 'ILGSM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'CHANGE_SIM_R', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'REQ_TYPE', 'NV', 'P_A', 'CHANGE_SIM_R', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'CHANGE_SIM_R', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'CHANGE_SIM_R', 'UNKNOWN');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('Speed Profile', 'NV', 'SO1_SERVICEID', 'NV', 'P_A', 'CHANGE_SIM_R', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'CHANGE_SIM_R', 'CHANGE_SIM_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERTYPE', 'NV', 'P_A', 'CHANGE_SIM_R', 'Change SIM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERSUBTYPE', 'NV', 'P_A', 'CHANGE_SIM_R', 'DEFAULT');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_ACTIONCODE', 'NV', 'P_A', 'CHANGE_SIM_R', 'Change SIM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_TECHNICALPRODUCT', 'NV', 'P_A', 'CHANGE_SIM_R', 'TP_ATHEEB');

-- DISCONNECT
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('IMSI Number', 'NV', 'SO1_IMSI1', 'NV', 'P_A', 'DISCONNECT', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('PrimaryPhoneNumber', 'NV', 'SO1_MSISDN1', 'NV', 'P_A', 'DISCONNECT', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'NE_TYPE', 'NV', 'P_A', 'DISCONNECT', 'ILGSM');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('orderNumber', 'OH', 'ORDER_NO', 'NV', 'P_A', 'DISCONNECT', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'REQ_TYPE', 'NV', 'P_A', 'DISCONNECT', '2');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values('createdBy', 'OH', 'REQ_USER', 'NV', 'P_A', 'DISCONNECT', '');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'RESP_QUEUE_ID', 'NV', 'P_A', 'DISCONNECT', 'UNKNOWN');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_SERVICE_TYPE', 'NV', 'P_A', 'DISCONNECT', 'DEL_SUBS_ATHEEB');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERTYPE', 'NV', 'P_A', 'DISCONNECT', 'Disconnect');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'ORDERSUBTYPE', 'NV', 'P_A', 'DISCONNECT', 'DEFAULT');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_ACTIONCODE', 'NV', 'P_A', 'DISCONNECT', 'Deleted');
insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(null, null, 'SO1_TECHNICALPRODUCT', 'NV', 'P_A', 'DISCONNECT', 'TP_ATHEEB');

commit;


-- =CONCAT("insert into STCW_COM_TO_LTE_DATA (COM_NAME, COM_ELEMENT, IF_NAME, IF_ELEMENT, SYSTEM, OPERATION, DEFAULT_VALUE) values(";IF(ISBLANK(B6);"null";CONCAT("'";B6;"'"));", ";IF(ISBLANK(C6);"null";CONCAT("'";C6;"'"));", '";D6;"', '";E6;"', 'P_A', '";F6;"', '";G6;"');")