alter index CWFELOG0 /* CWPROCESSEVENTLOG(EVENT_ID) */ rebuild compress 1;

alter table CWPROCESSEVENTLOG drop constraint CWPK_PROCESSEVENTLOG;
drop index CWPK_PROCESSEVENTLOG /* CWPROCESSEVENTLOG(EVENT_ID) */ ;

alter table CWPROCESSEVENTLOG add constraint CWPK_PROCESSEVENTLOG primary key (EVENT_ID)
using index GLOBAL PARTITION BY HASH (EVENT_ID)
     (PARTITION p1   TABLESPACE CWE_NDX,
      PARTITION p2   TABLESPACE CWE_NDX,
      PARTITION p3   TABLESPACE CWE_NDX,
      PARTITION p4   TABLESPACE CWE_NDX,
      PARTITION p5   TABLESPACE CWE_NDX,
      PARTITION p6   TABLESPACE CWE_NDX,
      PARTITION p7   TABLESPACE CWE_NDX,
      PARTITION p8   TABLESPACE CWE_NDX,
      PARTITION p9   TABLESPACE CWE_NDX,
      PARTITION p10  TABLESPACE CWE_NDX,
      PARTITION p11  TABLESPACE CWE_NDX,
      PARTITION p12  TABLESPACE CWE_NDX);
