-- STCW_PICKLIST_FOR_VALIDATION - NNI
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE)
  select max(to_number(CWDOCID) + 1) , 'lineItemType', 'NNI'
    from STCW_PICKLIST_FOR_VALIDATION;


-- STCW_SERVICETYPES_HIERARCHY - C041 -> C034
insert into STCW_SERVICETYPES_HIERARCHY(CWDOCID, PARENT_SERVICETYPE, CHILD_SERVICETYPE)
  select max(to_number(CWDOCID) + 1) , 'C041', 'C034'
    from STCW_SERVICETYPES_HIERARCHY;

-- STCW_SERVICETYPES_HIERARCHY - C041 -> C035
insert into STCW_SERVICETYPES_HIERARCHY(CWDOCID, PARENT_SERVICETYPE, CHILD_SERVICETYPE)
  select max(to_number(CWDOCID) + 1) , 'C041', 'C035'
    from STCW_SERVICETYPES_HIERARCHY;

    
insert into STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM)
values ('C034', 'C041', 'W');

insert into STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM)
values ('C035', 'C041', 'W');

commit;
