define DEFAULT_TABLESPACE_TABLE = CWE;
define DEFAULT_TABLESPACE_INDEX = CWE_NDX;

CREATE TABLE STC_STOREFORWARD_NVPAIR(
	NAME VARCHAR2(100) NOT NULL,
	CONSTRAINT PK_STC_STOREFORWARD_NVPAIR PRIMARY KEY(NAME) USING INDEX
	(CREATE UNIQUE INDEX PK_STC_STOREFORWARD_NVPAIR ON STC_STOREFORWARD_NVPAIR(NAME) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;