insert into STCW_PRODUCTCODE(PRODUCTCODE) values ('E050');
insert into STCW_SERVICETYPE_NAME_MAP(COM_SERVICETYPE, GI_SERVICETYPE) values ('E050', 'E050');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('E050', 'E050', 'W');

insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select 0, 'I', 'E050', 'CLLI' from dual;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'I', 'E050', 'Site Owner' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'I', 'E050', 'OLO ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'I', 'E050', 'Forced Sharing' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'I', 'E050', 'City' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'I', 'E050', 'Site Type' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'I', 'E050', 'Latitude' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'I', 'E050', 'Longitude' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'I', 'E050', 'Design Approval Date' from STCW_NVNAMES_MANDATORY;

insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'C', 'E050', 'CLLI' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'C', 'E050', 'Site Owner' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'C', 'E050', 'OLO ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'C', 'E050', 'Forced Sharing' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'C', 'E050', 'City' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'C', 'E050', 'Site Type' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'C', 'E050', 'Latitude' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'C', 'E050', 'Longitude' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'C', 'E050', 'Design Approval Date' from STCW_NVNAMES_MANDATORY;

insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'F', 'E050', 'CLLI' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'F', 'E050', 'Site Owner' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'F', 'E050', 'OLO ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'F', 'E050', 'Forced Sharing' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'F', 'E050', 'City' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'F', 'E050', 'Site Type' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'F', 'E050', 'Latitude' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'F', 'E050', 'Longitude' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'F', 'E050', 'Design Approval Date' from STCW_NVNAMES_MANDATORY;

insert into STCW_COM_TO_GRANITE_VALUE(ATTRIBUTENAME, COMATTRIBUTEVALUE, GRANITEATTRIBUTEVALUE) values ('FACILITY_BW', 'ANY', '*ANY*');
commit;
