define DEFAULT_TABLESPACE_TABLE = CWE;
define DEFAULT_TABLESPACE_INDEX = CWE_NDX;


CREATE TABLE STC_OM_HOME_SIP (
  CWDOCID             VARCHAR2(16),
  ACCOUNTNUMBER       VARCHAR2(50),
  COMPLETION_DATE     DATE,
  CREATEDBY           VARCHAR2(50),
  CREATIONDATE        DATE,
  CUSTOMERCONTACT     VARCHAR2(50),
  CUSTOMERIDNUMBER    VARCHAR2(50),
  CUSTOMERIDTYPE      VARCHAR2(50),
  CUSTOMERNAME        NVARCHAR2(60),
  CUSTOMERNUMBER      VARCHAR2(50),
  CUSTOMERTYPE        VARCHAR2(50),
  ICMSSONUMBER        VARCHAR2(12),
  PARENTORDERNUMBER   VARCHAR2(50),
  ORDERSTATUS         VARCHAR2(50),
  ORDERTYPE           VARCHAR2(25),
  PRIORITY            VARCHAR2(25),
  CWORDERCREATIONDATE DATE,
  REFERENCETELNUMBER  VARCHAR2(50),
  REMARKS             VARCHAR2(4000),
  SERVICEDATE         DATE,
  FICTBILLINGNUMBER   VARCHAR2(50),
  CIRCUITNUMBER       VARCHAR2(100),
  BANDWIDTH           VARCHAR2(30),
  CIRCUITSTATUS       VARCHAR2(50),
  COMMONPLATEID       VARCHAR2(50),
  OLDCIRCUITNUMBER    VARCHAR2(100),
  PROJECTID           VARCHAR2(50),
  TBPORTNUMBER        VARCHAR2(50),
  WIRES               VARCHAR2(25),
  ORDERNUMBER         VARCHAR2(50),
  CWORDERID           VARCHAR2(16),
  CCTTYPE             VARCHAR2(25),
  ISINARCHIVE         NUMBER(1),
  MIGRATEDTOBUNDLE    NUMBER(1),
  CONSTRAINT PK_STC_OM_HOME_SIP PRIMARY KEY(CWDOCID) USING INDEX
  (CREATE UNIQUE INDEX PK_STC_OM_HOME_SIP ON STC_OM_HOME_SIP(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

CREATE INDEX IDX_OM_HOME_CWORDID ON STC_OM_HOME_SIP (CWORDERID)
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

ALTER TABLE STC_OM_HOME_SIP
  ADD CONSTRAINT UK_OM_HOME_ORDNUM UNIQUE (ORDERNUMBER)
  USING INDEX
  TABLESPACE &DEFAULT_TABLESPACE_INDEX;

CREATE INDEX IDX_OM_HOME_PARENTORDERNUMBER ON STC_OM_HOME_SIP (PARENTORDERNUMBER)
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

CREATE TABLE STC_SP_HOME_SIP (
  CWDOCID             VARCHAR2(16),
  CREATIONDATE        DATE,
  SERVICENUMBER       VARCHAR2(50),
  TOBECANCELLED       NUMBER(1),
  OLDPLATEID          VARCHAR2(50),
  PLATEID             VARCHAR2(50),
  UNITNUMBER          VARCHAR2(50),
  SERVICEDATE         DATE,
  SERVICEDESCRIPTION  VARCHAR2(1000),
  ORDERROWITEMID      VARCHAR2(50),
  OLDSERVICENUMBER    VARCHAR2(50),
  SERVICETYPE         VARCHAR2(25),
  CWORDERID           VARCHAR2(16),
  CONSTRAINT PK_STC_SP_HOME_SIP PRIMARY KEY(CWDOCID) USING INDEX
  (CREATE UNIQUE INDEX PK_STC_SP_HOME_SIP ON STC_SP_HOME_SIP(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

CREATE INDEX IDX_SP_HOME_CWORDID on STC_SP_HOME_SIP (CWORDERID)
TABLESPACE &DEFAULT_TABLESPACE_INDEX;



CREATE TABLE STC_NV_HOME_SIP (
  CWDOCID             VARCHAR2(16),
  NAME                VARCHAR2(100),
  VALUE               VARCHAR2(4000),
  CWORDERID           VARCHAR2(16),
  SERVICEDOCID        VARCHAR2(16),
  CONSTRAINT PK_STC_NV_HOME_SIP PRIMARY KEY(CWDOCID) USING INDEX
  (CREATE UNIQUE INDEX PK_STC_NV_HOME_SIP ON STC_NV_HOME_SIP(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

CREATE INDEX IDX_NV_HOME_CWORDID on STC_NV_HOME_SIP (CWORDERID)
TABLESPACE &DEFAULT_TABLESPACE_INDEX;



CREATE TABLE STC_HOME_SIP_FROMCRM (
	CWDOCID VARCHAR2(16) NOT NULL,
	PARENT_ORDER_NUMBER VARCHAR2(50),
	OPERATION VARCHAR2(256),
	REC_ORDER_STATUS VARCHAR2(50),
	CREATION_TIME DATE,
	CONSTRAINT PK_STC_HOME_FROMCRM  PRIMARY KEY(CWDOCID) USING INDEX
	(CREATE UNIQUE INDEX PK_STC_HOME_FROMCRM  ON STC_HOME_SIP_FROMCRM(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

CREATE INDEX STC_HOME_FROMCRM_ORDNUM ON STC_HOME_SIP_FROMCRM (PARENT_ORDER_NUMBER)
TABLESPACE &DEFAULT_TABLESPACE_INDEX;


CREATE TABLE SIP_ORDERS_EXCLUDED_FROM_MIGR (
  CWORDERID VARCHAR2(16) NOT NULL,
  ORDER_NUMBER  VARCHAR2(50) NOT NULL
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;
 

 
CREATE TABLE STC_SIP_WORKAROUND_DATA (
  CWORDERID VARCHAR2(16) NOT NULL,
  CUSTOMERNAME VARCHAR2(60),
  CUSTOMERNAME_ORIG NVARCHAR2(60),
  SERVICEDESCRIPTION VARCHAR2(50),
  SERVICEDESCRIPTION_ORIG VARCHAR2(1000),
	CONSTRAINT PK_STC_SIP_WORKAROUND_DATA PRIMARY KEY(CWORDERID) USING INDEX
	(CREATE UNIQUE INDEX PK_STC_SIP_WORKAROUND_DATA ON STC_SIP_WORKAROUND_DATA(CWORDERID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;


CREATE TABLE STC_SIP_CRM_DATA (
  ORDERCUSTOMERNUMBER VARCHAR2(50),
  ORDERACCOUNTNUMBER VARCHAR2(50),
  BUNDLEID VARCHAR2(255) NOT NULL,
  BUNDLEFICTB# VARCHAR2(50),
  CIRCUITNUMBER VARCHAR2(255) NOT NULL,
  CIRCUITFICTB#	VARCHAR2(50),
  CHILDCIRCUITID VARCHAR2(255) NOT NULL,
  CHILDSERVICENUMBER VARCHAR2(255),
  CHILDEQUIVALENTSERVICENUMBER VARCHAR2(255),
  CHILDFICTB#	VARCHAR2(50),
  USED CHAR(1),
	CONSTRAINT PK_STC_SIP_CRM_DATA PRIMARY KEY(CIRCUITNUMBER) USING INDEX
	(CREATE UNIQUE INDEX PK_STC_SIP_CRM_DATA ON STC_SIP_CRM_DATA(CIRCUITNUMBER) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;


CREATE TABLE STC_AMO_NAME_BCK (
  OLD_SERVICE#   VARCHAR2(255),
  OLD_IDENTIFIER VARCHAR2(255),
  NEW_SERVICE#   VARCHAR2(255),
  NEW_IDENTIFIER VARCHAR2(255),
  CWDOCID        VARCHAR2(16))
TABLESPACE &DEFAULT_TABLESPACE_TABLE;