define DEFAULT_TABLESPACE_TABLE = CWE;
define DEFAULT_TABLESPACE_INDEX = CWE_NDX;

DROP INDEX STC_BO_HEADER_ORDERNUMBER;

ALTER TABLE STC_BUNDLEORDER_HEADER
ADD CONSTRAINT STC_BO_HEADER_ORDERNUMBER UNIQUE (ORDERNUMBER)
USING INDEX 
TABLESPACE &DEFAULT_TABLESPACE_INDEX;


CREATE TABLE STC_BUNDLE_PRODUCTTYPE(
	PRODUCTTYPE VARCHAR2(255) NOT NULL,
	CONSTRAINT PK_STC_BUNDLE_PRODUCTTYPE PRIMARY KEY(PRODUCTTYPE) USING INDEX
	(CREATE UNIQUE INDEX PK_STC_BUNDLE_PRODUCTTYPE ON STC_BUNDLE_PRODUCTTYPE(PRODUCTTYPE) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

INSERT INTO STC_BUNDLE_PRODUCTTYPE VALUES('SIPB');
INSERT INTO STC_BUNDLE_PRODUCTTYPE VALUES('MATM');

COMMIT;