insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH) values ('BD053', 0, 'DEFAULT');
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH) values ('BD054', 0, 'DEFAULT');
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH) values ('BD055', 0, 'DEFAULT');
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH) values ('BD058', 0, 'DEFAULT');

commit;
