insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('BD053', 'BD053', 'E');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('BD054', 'BD054', 'E');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('BD055', 'BD055', 'E');
insert into STCW_BU_PROVISIONING(SERVICETYPE, PRODUCTCODE, CIM) values ('BD058', 'BD058', 'E');

commit;
