insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'F', 'BD053', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'F', 'BD054', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'F', 'BD055', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'F', 'BD058', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;

insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'I', 'BD053', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'I', 'BD054', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'I', 'BD055', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'I', 'BD058', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;

insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'C', 'BD053', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'C', 'BD054', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'C', 'BD055', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'C', 'BD058', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;

insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'O', 'BD053', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'O', 'BD054', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'O', 'BD055', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;
insert into STCW_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(CWDOCID)) + 1, 'O', 'BD058', 'Primary_Circuit_ID' from STCW_NVNAMES_MANDATORY;

commit;
