/***

define DEFAULT_TABLESPACE_TABLE = CWE;
define DEFAULT_TABLESPACE_INDEX = CWE_NDX;

***/


define DEFAULT_TABLESPACE_TABLE = STC_DATA;
define DEFAULT_TABLESPACE_INDEX = STC_DATA;


drop table STC_SERVICE_MIGRATION;
create table STC_SERVICE_MIGRATION (
  CUSTOMER_NUMBER varchar2(100),
  CUSTOMER_NAME varchar2(500),
  ACCOUNT_NUMBER varchar2(100),
  PATH_NAME varchar2(100),
  ECNM_MIGRATION varchar2(500),
  ACCESS_NUMBER varchar2(100),
  MVPN_MOBILE_NUMBER varchar2(1000),
  MSISDN varchar2(1000),
  ASSET_STATUS varchar2(500),
  SITE_A varchar2(100),
  SITE_B varchar2(100),
  CIRCUIT_CATEGORY varchar2(255),
  BANDWIDTH varchar2(30),
  MVPN_SPEED varchar2(1000),
  SIM_NUMBER varchar2(1000),
  MVPN_ACCESS_TYPE varchar2(1000),
  IMSI_NUMBER varchar2(1000),
  REGISTRATION_ID varchar2(1000),
  ASSET_CREATED varchar2(1000),
  RTN_CIRCUIT_SPEED varchar2(1000),
  FUNCTION_CODE varchar2(100),
  ORDER_NUMBER varchar2(50),
  MIGRATION_RESULT number(2) default 0,
  FAILURE_DESCRIPTION varchar2(2000)
)
tablespace &DEFAULT_TABLESPACE_TABLE;

-- Create/Recreate primary, unique and foreign key constraints 
alter table STC_SERVICE_MIGRATION
  add constraint PK_STC_SERVICE_MIGRATION primary key (ORDER_NUMBER)
  using index 
  tablespace &DEFAULT_TABLESPACE_INDEX;

create index STC_SERV_MIGR_PATHNAME_IDX on STC_SERVICE_MIGRATION (PATH_NAME)
  tablespace &DEFAULT_TABLESPACE_INDEX;
  
create index STC_SERV_MIGR_MIGRRES_IDX on STC_SERVICE_MIGRATION (MIGRATION_RESULT)
  tablespace &DEFAULT_TABLESPACE_INDEX;