insert into CWCALENDARTEMPLATE (TEMPLATE, NAME, TYPE, DAY, MONTH, WEEKDAY, SPEC, DAYTYPE, SCRIPT, WORK_HOUR1, WORK_HOUR2, WORKING)
values ('STC', 'Weekend', 0, 96, 0, 0, 0, 0, null, null, null, 0);

insert into CWCALENDARTEMPLATE (TEMPLATE, NAME, TYPE, DAY, MONTH, WEEKDAY, SPEC, DAYTYPE, SCRIPT, WORK_HOUR1, WORK_HOUR2, WORKING)
values ('STC', 'New Year Day', 3, 1, 0, 0, 0, 1, null, null, null, 0);


insert into CWCALENDARS (CALENDAR, TEMPLATE, WORK_FROM, WORK_TO, FIRST_DAY, LABEL, TOTAL_YEARS_COVERED, PAST_YEARS_COVERED)
values ('STC_Calendar', 'STC', 800, 1700, 1, 'STC', 9, 1);

update CWROLE set CALENDAR = 'STC_Calendar';

commit;
