prompt Dropping ALL TFS tables...

-- DATA MODEL
DROP TABLE STC_TFR_TASK;

DROP TABLE STC_BI_CUSTOMATTR;
DROP TABLE STC_BI;

ALTER TABLE STC_PRN DROP CONSTRAINTS FK_STC_PRN_TFR_ID;
DROP TABLE STC_TFR_CUSTOMATTR;
DROP TABLE STC_TFR;

DROP TABLE STC_REJECTION_PROCESS_ACTIVITY;
DROP TABLE STC_REJECTION_PROCESS;
DROP TABLE STC_PRN_CUSTOMATTR;
DROP TABLE STC_PRN;
DROP TABLE STC_PRNR_CUSTOMATTR;
DROP TABLE STC_PRNR;

DROP TABLE STC_REJECTION_PROCESS_DATA;

-- CONFIGURATION
ALTER TABLE CWPWORKLIST DROP COLUMN OBJ_CREATION_DATE;
ALTER TABLE CWPWORKLIST DROP COLUMN OBJ_PLANNED_RFS_DATE;
ALTER TABLE CWPWORKLIST DROP COLUMN CUSTOMER_NAME;
ALTER TABLE CWPWORKLIST DROP COLUMN OBJECT_TYPE;
ALTER TABLE CWPWORKLIST DROP COLUMN OBJECT_NAME;
ALTER TABLE CWPWORKLIST DROP COLUMN OBJECT_ID;
ALTER TABLE CWPWORKLIST DROP COLUMN OBJECT_STATUS;
ALTER TABLE CWPWORKLIST DROP COLUMN REQUESTER;

DROP TABLE STC_OPERATION_ASSIGNMENT_RULE;
DROP TABLE STC_PICKLIST;
DROP TABLE STC_CUSTOMATTR_LIST_OPTION;
DROP TABLE STC_CUSTOMATTR;
DROP TABLE STC_MAP_DOC2DOC;
DROP TABLE STC_MANDATORY_ATTR;
DROP TABLE STC_STATUS_MAPPING;
ALTER TABLE STC_REJECT_ANSWER DROP CONSTRAINTS FK_STC_REJECT_ANSWER_QUESTION;
DROP TABLE STC_REJECT_QUESTION;
DROP TABLE STC_REJECT_ANSWER;


DROP VIEW STC_PRIVILEGE_V;

-- UTILITY
DROP TABLE STC_USERS4ORDER;
DROP TABLE STC_TRACKING;
DROP TABLE STC_ROUNDROBIN_MGMT;
DROP TABLE STC_PROCESS_ADDITIONALINFO;

