prompt Creating CONFIGURATION tables...

@define_variables.sql


ALTER TABLE CWPWORKLIST ADD (
  OBJ_CREATION_DATE DATE,
  OBJ_PLANNED_RFS_DATE DATE,
  CUSTOMER_NAME VARCHAR2(100),
  OBJECT_TYPE VARCHAR2(30),
  OBJECT_NAME VARCHAR2(100),
  OBJECT_ID VARCHAR2(16),
  OBJECT_STATUS VARCHAR2(100),
  REQUESTER VARCHAR2(64)
);


CREATE TABLE STC_OPERATION_ASSIGNMENT_RULE (
  PROCESS_NAME VARCHAR2(256) NOT NULL,
  OPERATION_NAME VARCHAR2(256) NOT NULL,
  PRIVILEGE_CODE VARCHAR2(16) NOT NULL,
  INTERNAL_PARTICIPANT_NAME VARCHAR2(20) NOT NULL,
  ASSIGNMENT VARCHAR2(100) DEFAULT 'Load Balancing',
  EMAIL_NOTIFICATION NUMBER(1) DEFAULT 0
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_OPERATION_ASSIGNMENT_RULE
ADD CONSTRAINT PK_STC_OPERATION_ASSIGNRULE PRIMARY KEY(PROCESS_NAME, OPERATION_NAME)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;  

ALTER TABLE STC_OPERATION_ASSIGNMENT_RULE
ADD CONSTRAINT FK_STC_OP_ASSIGNRULE_PRIVILEGE FOREIGN KEY(PRIVILEGE_CODE)
REFERENCES CWPRIVILEGE (PRIVILEGE);

ALTER TABLE STC_OPERATION_ASSIGNMENT_RULE
ADD CONSTRAINT ASSIGNMENT_LISTS
CHECK (ASSIGNMENT IN ('Direct', 'Round Robin', 'To Manager', 'Load Balancing', 'To Shared List'));



CREATE TABLE STC_CUSTOMATTR (
  CUSTOMATTR_ID VARCHAR2(16) NOT NULL,
  PARENT_ELEMENT VARCHAR2(30) NOT NULL,
  ATTRIBUTE_NAME VARCHAR2(100) NOT NULL,
  ATTRIBUTE_TYPE VARCHAR2(10) NOT NULL,
  HYPERLINK_ATTR_NAME VARCHAR2(100)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_CUSTOMATTR
ADD CONSTRAINT PK_STC_CUSTOMATTR PRIMARY KEY(CUSTOMATTR_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;  

ALTER TABLE STC_CUSTOMATTR
ADD CONSTRAINT UK_STC_CUSTOMATTR_ATTRNAME UNIQUE(PARENT_ELEMENT, ATTRIBUTE_NAME)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;  

ALTER TABLE STC_CUSTOMATTR
ADD CONSTRAINT ATTRIBUTE_TYPE_LISTS
CHECK (ATTRIBUTE_TYPE IN ('String', 'Date', 'PickList', 'Hyperlink'));



CREATE TABLE STC_CUSTOMATTR_LIST_OPTION (
  CWDOCID VARCHAR2(16) NOT NULL,
  CUSTOMATTR_ID VARCHAR2(16) NOT NULL,
  ATTRIBUTE_VALUE VARCHAR2(1000) NOT NULL,
  SEQUENCE_NUMBER NUMBER(3)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_CUSTOMATTR_LIST_OPTION
ADD CONSTRAINT PK_STC_CUSTOMATTR_OPTS PRIMARY KEY(CWDOCID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;  

ALTER TABLE STC_CUSTOMATTR_LIST_OPTION
ADD CONSTRAINT UK_STC_CUSTOMATTR_OPTS_VAL UNIQUE(CUSTOMATTR_ID, ATTRIBUTE_VALUE)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;  

ALTER TABLE STC_CUSTOMATTR_LIST_OPTION
ADD CONSTRAINT FK_STC_CUSTOMATTR_OPTS_CATTR FOREIGN KEY(CUSTOMATTR_ID)
REFERENCES STC_CUSTOMATTR (CUSTOMATTR_ID) ON DELETE CASCADE;



CREATE TABLE STC_MAP_DOC2DOC (
  DEST_OBJECT VARCHAR2(20) NOT NULL,
  DEST_FIELD VARCHAR2(100) NOT NULL,
  SOURCE_OBJECT VARCHAR2(20) NOT NULL,
  SOURCE_FIELD VARCHAR2(100) NOT NULL
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_MAP_DOC2DOC
ADD CONSTRAINT UK_STC_MAP_DOC2DOC UNIQUE(DEST_OBJECT, DEST_FIELD, SOURCE_OBJECT, SOURCE_FIELD)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;  



CREATE TABLE STC_MANDATORY_ATTR (
  MANDATORY_ID VARCHAR2(16) NOT NULL,
  OBJECT_TYPE VARCHAR2(30) NOT NULL,
  FIELD_NAME VARCHAR2(100) NOT NULL
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_MANDATORY_ATTR
ADD CONSTRAINT PK_STC_MANDATORY_ATTR PRIMARY KEY(MANDATORY_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;  

ALTER TABLE STC_MANDATORY_ATTR
ADD CONSTRAINT UK_STC_MANDATORY_ATTR UNIQUE(OBJECT_TYPE, FIELD_NAME)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;  



CREATE TABLE STC_STATUS_MAPPING (
  STATUS_MAPPING_ID VARCHAR2(16) NOT NULL,
  OBJECT_TYPE VARCHAR2(30) NOT NULL,
  INTERNAL_STATUS VARCHAR2(100) NOT NULL,
  GUI_STATUS VARCHAR2(100) NOT NULL
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_STATUS_MAPPING
ADD CONSTRAINT PK_STC_STATUS_MAPPING PRIMARY KEY(STATUS_MAPPING_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;  

ALTER TABLE STC_STATUS_MAPPING
ADD CONSTRAINT UK_STC_STATUS_INTERNAL UNIQUE(OBJECT_TYPE, INTERNAL_STATUS)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;  

ALTER TABLE STC_STATUS_MAPPING
ADD CONSTRAINT UK_STC_STATUS_GUI UNIQUE(OBJECT_TYPE, GUI_STATUS)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX; 



CREATE TABLE STC_REJECT_QUESTION (
  QUESTION_ID VARCHAR2(16) NOT NULL,
  PARENT_ANSWER_ID VARCHAR2(16),
  TEXT_QUESTION VARCHAR2(1000) NOT NULL
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_REJECT_QUESTION
ADD CONSTRAINT PK_STC_REJECT_QUESTION PRIMARY KEY(QUESTION_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;  



CREATE TABLE STC_REJECT_ANSWER (
  ANSWER_ID VARCHAR2(16) NOT NULL,
  PARENT_QUESTION_ID VARCHAR2(16),
  TEXT_ANSWER VARCHAR2(1000) NOT NULL,
  RESPONSE_TO_RETURN VARCHAR2(100)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_REJECT_ANSWER
ADD CONSTRAINT PK_STC_REJECT_ANSWER PRIMARY KEY(ANSWER_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;  

ALTER TABLE STC_REJECT_QUESTION
ADD CONSTRAINT FK_STC_REJECT_QUESTION_ANSWER FOREIGN KEY(PARENT_ANSWER_ID)
REFERENCES STC_REJECT_ANSWER(ANSWER_ID);  

ALTER TABLE STC_REJECT_ANSWER
ADD CONSTRAINT FK_STC_REJECT_ANSWER_QUESTION FOREIGN KEY(PARENT_QUESTION_ID)
REFERENCES STC_REJECT_QUESTION(QUESTION_ID);  


--Configuration for Revise and Readonly attributes
-- ADD CONSTRAINT UK_STC_STATUS_INTERNAL UNIQUE(OBJECT_TYPE, INTERNAL_STATUS)
CREATE TABLE STC_REVISABLE_ATTR(
  REVISABLE_ID VARCHAR2(16) NOT NULL,
  OBJECT_TYPE VARCHAR2(30),
  FIELD_NAME VARCHAR2(100),
  CONSTRAINT PK_STC_REVISABLE_ATTR PRIMARY KEY(REVISABLE_ID) USING INDEX
  (CREATE UNIQUE INDEX PK_STC_REVISABLE_ATTR ON STC_REVISABLE_ATTR(REVISABLE_ID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_REVISABLE_ATTR
ADD CONSTRAINT UK_STC_REVISABLE_ATTR UNIQUE (FIELD_NAME, OBJECT_TYPE)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX; 


CREATE TABLE STC_CITY_DISTRICT_REGION(
  CITY_NAME VARCHAR2(60) NOT NULL,
  DISTRICT_NAME VARCHAR2(60),
  REGION_CODE VARCHAR2(3),
  CONSTRAINT PK_STC_CITY_DISTRICT_REGION PRIMARY KEY(CITY_NAME) USING INDEX
  (CREATE UNIQUE INDEX PK_STC_CITY_DISTRICT_REGION ON STC_CITY_DISTRICT_REGION(CITY_NAME) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;



CREATE TABLE STC_READONLY_ATTR(
  CWDOCID VARCHAR2(16) NOT NULL,
  FIELD_NAME VARCHAR2(100),
  PRIVILEGE_NAME VARCHAR2(128),
  OBJECT_TYPE VARCHAR2(30),
  CONSTRAINT PK_STC_READONLY_ATTR PRIMARY KEY(CWDOCID) USING INDEX
  (CREATE UNIQUE INDEX PK_STC_READONLY_ATTR ON STC_READONLY_ATTR(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_READONLY_ATTR
ADD CONSTRAINT UK_STC_READONLY_ATTR UNIQUE(FIELD_NAME, OBJECT_TYPE, PRIVILEGE_NAME)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;  




COMMIT;

