prompt Creating UTILITY tables...

@define_variables.sql

CREATE TABLE STC_USERS4ORDER (
  CWDOCID VARCHAR2(16) NOT NULL,
  ORDER_ID VARCHAR2(16) NOT NULL,
  ORDERITEMID VARCHAR2(16),
  USERID_INITIATOR VARCHAR2(64),
  USERID_INTEGRATION VARCHAR2(64),
  USERID_NETWORKDESIGN VARCHAR2(64),
  USERID_FACILITYDESIGN VARCHAR2(64),
  USERID_XC VARCHAR2(64),
  USERID_SWITCHACTIVATION varchar2(64),
  USERID_QUALITY VARCHAR2(64),
  USERID_SITE VARCHAR2(64),
  USERID_VERIFICATION varchar2(64),
  USERID_BI varchar2(64),
  USERID_TRANSPORT_MAPPING VARCHAR2(64),
  USERID_BB_TRANSPORT_DESIGN VARCHAR2(64),
  USERID_FATX VARCHAR2(64),
  USERID_TFA_MODSQUAD VARCHAR2(64),
  USERID_TFA VARCHAR2(64),
  USERID_AS VARCHAR2(64),
  USERID_FNI VARCHAR2(64),
  USERID_ASBUILT VARCHAR2(64),
  IS_DEF_PROC NUMBER(1) default 1
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_USERS4ORDER
ADD CONSTRAINT PK_STC_USERS4ORDER PRIMARY KEY(CWDOCID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;



CREATE TABLE STC_TRACKING (
  CWDOCID VARCHAR2(16) NOT NULL,
  WL_ID VARCHAR2(16) NOT NULL,
  PROCESS_ID NUMBER(16),
  ORDER_ID VARCHAR2(16) NOT NULL,
  OBJECT_ID VARCHAR2(16) NOT NULL,
  OBJECT_TYPE VARCHAR2(30) NOT NULL,
  OPERATION_NAME VARCHAR2(256) NOT NULL,
  ASSIGN_TO_USER_DATE DATE,
  COMPLETION_DATE DATE,
  PERFORMED_TASK_NAME VARCHAR2(256),
  USER_ID VARCHAR2(64)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_TRACKING
ADD CONSTRAINT PK_STC_TRACKING PRIMARY KEY(CWDOCID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;



CREATE TABLE STC_ROUNDROBIN_MGMT (
  CWDOCID VARCHAR2(16) NOT NULL,
  USER_ID VARCHAR2(64) NOT NULL,
  TOKEN   NUMBER(1) DEFAULT 0
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_ROUNDROBIN_MGMT
ADD CONSTRAINT PK_STC_ROUNDROBIN_MGMT PRIMARY KEY(CWDOCID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;



CREATE TABLE STC_PROCESS_ADDITIONALINFO(
	PROCESS_ID VARCHAR2(16),
	EMAIL_NOTIFICATION NUMBER(1)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_PROCESS_ADDITIONALINFO
ADD CONSTRAINT PK_STC_PROCESS_ADDITIONALINFO PRIMARY KEY(PROCESS_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;


CREATE TABLE STC_DATA_4_BI_ASSOC_PROCESS (
  PROCESS_ID NUMBER(16) NOT NULL,
  PARENT_PROCESS_ID NUMBER(16),
  REQUEST_NOTIFICATION NUMBER(1),
  PRN_SOURCE NUMBER(1)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_DATA_4_BI_ASSOC_PROCESS
ADD CONSTRAINT PK_STC_DATA_4_BI_ASSOC_PROCESS PRIMARY KEY(PROCESS_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;


CREATE TABLE STC_OBJECT_REMARKS(
  CWDOCID       VARCHAR2(16) NOT NULL,
  OBJECT_ID     VARCHAR2(16) NOT NULL,
  CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
  USERID        VARCHAR2(64) NOT NULL,
  REMARK_TEXT   VARCHAR2(4000),
  OBJECT_TYPE   VARCHAR2(30) NOT NULL,
  ORDER_ID      VARCHAR2(16)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_OBJECT_REMARKS
ADD CONSTRAINT PK_STC_OBJ_REMARKS PRIMARY KEY(CWDOCID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;
