prompt Creating PRNR tables...

@define_variables.sql


CREATE TABLE STC_PRNR(
	PRNR_ID VARCHAR2(16) NOT NULL,
	PRNR_NAME VARCHAR2(16) NOT NULL,
	PRNR_STATUS VARCHAR2(100) NOT NULL,
	CUSTOMER_NAME VARCHAR2(100),
	RELEASED_DATE DATE,
	SITE_A_NAME VARCHAR2(100),
	SITE_A_IF VARCHAR2(100),
	SITE_A_JVC VARCHAR2(100),
	SITE_Z_NAME VARCHAR2(100),
	SITE_Z_IF VARCHAR2(100),
	SITE_Z_JVC VARCHAR2(100),
	REQUIREMENT_TYPE VARCHAR2(100),
	QUANTITY NUMBER(2),
	CURRENT_USERID VARCHAR2(64),
	BU_INITIATOR VARCHAR2(128),
	TRAFFIC_DIVERSITY VARCHAR2(100),
	PROTECTION_TYPE VARCHAR2(100),
	STRUCTURE_TYPE VARCHAR2(100),
	TRAFFIC_TYPE VARCHAR2(100),
	SERVICE_TYPE VARCHAR2(100),
	CREATION_DATE DATE,
	PLANNED_RFS_DATE DATE,
	PRNR_YEAR VARCHAR2(4),
	PRNR_MONTH VARCHAR2(2),
	CUSTOMER_PROJECT VARCHAR2(100),
	CUSTOMER_PROJECT_PHASE VARCHAR2(100),
	CUSTOMER_PLAN_NUM VARCHAR2(30),
	CUSTOMER_RN VARCHAR2(30),
	BENEFICIARY_NAME VARCHAR2(30),
	BENEFICIARY_CONTACTS VARCHAR2(150),
	CREATED_BY VARCHAR2(64) NOT NULL,
	CUSTOMER_SITE VARCHAR2(100),
	GSM_CELL_ID VARCHAR2(100),
	TECH_TYPE VARCHAR2(100),
	GSM_CELL_VENDOR VARCHAR2(100),
	TN VARCHAR2(100),
	TN_PORT VARCHAR2(50),
	AFFECTED_PRNR VARCHAR2(50),
	ISOW_PROJECT VARCHAR2(100),
	CIRCUIT_NUMBER VARCHAR2(100),
	CWDOCSTAMP VARCHAR2(9),
	CWORDERCREATIONDATE DATE,
	CWORDERID VARCHAR2(16),
	CWPARENTID VARCHAR2(16),
	LASTUPDATEDDATE DATE,
	UPDATEDBY VARCHAR2(64),
	CONNECTION_TFR_ID VARCHAR2(16),
	PARENT_PROC_ID VARCHAR2(16),
	CHANGEDTFRID VARCHAR2(16),
	CANCELLED_DATE DATE,
	CURRENT_USER_DEPARTMENT VARCHAR2(100)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_PRNR
ADD CONSTRAINT PK_STC_PRNR PRIMARY KEY(PRNR_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

ALTER TABLE STC_PRNR
ADD CONSTRAINT UK_STC_PRNR_NAME UNIQUE(PRNR_NAME)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;



CREATE TABLE STC_PRNR_CUSTOMATTR (
	PRNR_ID VARCHAR2(16) NOT NULL,
	CUSTOMATTR_ID VARCHAR2(16) NOT NULL,
	ATTRIBUTE_VALUE VARCHAR2(1000)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_PRNR_CUSTOMATTR
ADD CONSTRAINT PK_STC_PRNR_CUSTOMATTR PRIMARY KEY(PRNR_ID, CUSTOMATTR_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

ALTER TABLE STC_PRNR_CUSTOMATTR
ADD CONSTRAINT FK_STC_PRNR_CUSTOMATTR_PRNR FOREIGN KEY(PRNR_ID)
REFERENCES STC_PRNR (PRNR_ID);

ALTER TABLE STC_PRNR_CUSTOMATTR
ADD CONSTRAINT FK_STC_PRNR_CUSTOMATTR_CATTR FOREIGN KEY(CUSTOMATTR_ID)
REFERENCES STC_CUSTOMATTR (CUSTOMATTR_ID);
