prompt Creating REJECTION_PROCESS tables...

@define_variables.sql

CREATE TABLE STC_REJECTION_PROCESS(
	PROCESS_ID VARCHAR2(16) NOT NULL,
	TFR_ID VARCHAR2(16),
	REJECTION_PROCESS_STATUS VARCHAR2(20),
	CREATION_DATE DATE,
	CREATED_BY VARCHAR2(64),
	COMPLETION_DATE DATE,
	CURRENT_USERID VARCHAR2(64)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_REJECTION_PROCESS
ADD CONSTRAINT PK_STC_REJPROC PRIMARY KEY(PROCESS_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

-- ALTER TABLE STC_REJECTION_PROCESS
-- ADD CONSTRAINT FK_STC_REJPROC_TFR_ID FOREIGN KEY(TFR_ID)
-- REFERENCES STC_TFR (TFR_ID) ON DELETE CASCADE;

CREATE TABLE STC_REJECTION_PROCESS_ACTIVITY(
  ACTIVITY_ID VARCHAR2(16) NOT NULL,
	PROCESS_ID VARCHAR2(16) NOT NULL,
	CREATION_DATE DATE,
	COMPLETION_DATE DATE,
  QUESTION_ID VARCHAR2(16),
  ANSWER_ID VARCHAR2(16),
  REMARKS VARCHAR2(4000)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_REJECTION_PROCESS_ACTIVITY
ADD CONSTRAINT PK_STC_REJPROC_ACT PRIMARY KEY(ACTIVITY_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

ALTER TABLE STC_REJECTION_PROCESS_ACTIVITY
ADD CONSTRAINT FK_STC_REJPROC_ACT_PROC_ID FOREIGN KEY(PROCESS_ID)
REFERENCES STC_REJECTION_PROCESS (PROCESS_ID) ON DELETE CASCADE;



CREATE TABLE STC_REJECTION_PROCESS_DATA(
  CWDOCID VARCHAR2(16) NOT NULL,
  QUESTION_ID VARCHAR2(16),
	CREATION_DATE DATE,
	PROCESS_ID VARCHAR2(16),
  ACTIVITY_PROCESS_ID VARCHAR2(16),
  SELECTED_ANSWER_ID VARCHAR2(16),
  TFR_ID VARCHAR2(16),
	PARENT_PROCESS_ID VARCHAR2(16),
  CURRENT_USERID VARCHAR2(64),
  REMARKS VARCHAR2(4000),
  CWDOCSTAMP VARCHAR2(9),
	CWORDERCREATIONDATE DATE,
	CWORDERID VARCHAR2(16),
	CWPARENTID VARCHAR2(16),
	LASTUPDATEDDATE DATE,
	UPDATEDBY VARCHAR2(64)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_REJECTION_PROCESS_DATA
ADD CONSTRAINT PK_STC_REJPROC_DATA PRIMARY KEY(CWDOCID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;
