prompt Creating TFR tables...

@define_variables.sql

CREATE TABLE STC_TFR(
  TFR_ID VARCHAR2(16) NOT NULL,
  TFR_NUMBER VARCHAR2(30) NOT NULL,
  TFR_STATUS  VARCHAR2(100) NOT NULL,
  SITE_A_NAME VARCHAR2(100),
  SITE_A_IF VARCHAR2(100),
  SITE_A_JVC VARCHAR2(100),
  SITE_A_EXCHANGETYPE VARCHAR2(100),
  SITE_A_TERMINATION VARCHAR2(100),
  SITE_A_SWITCH_TYPE VARCHAR2(100),
  SITE_Z_NAME VARCHAR2(100),
  SITE_Z_IF VARCHAR2(100),
  SITE_Z_JVC VARCHAR2(100),
  SITE_Z_EXCHANGETYPE VARCHAR2(100),
  SITE_Z_TERMINATION VARCHAR2(100),
  SITE_Z_SWITCH_TYPE VARCHAR2(100),
  REGION VARCHAR2(3),
  DISTRICT VARCHAR2(100),
  PLANNED_ISSUE_DATE DATE,
  CREATION_DATE DATE,
  PLANNED_RFS_DATE DATE,
  DEPT_CREATED_BY VARCHAR2(128),
  PRIORITY NUMBER(2),
  REASON_FOR_ISSUE  VARCHAR2(100),
  BU_REQUESTER  VARCHAR2(128) ,
  CUSTOMER_NAME VARCHAR2(100),
  GROUP_REQUESTER VARCHAR2(128),
  ICMS_NUMBER VARCHAR2(100),
  HAJJ_COMMITTMENT VARCHAR2(100),
  PRN_ID VARCHAR2(16),
  REQUIREMENT_TYPE VARCHAR2(100),
  EXISTING NUMBER(3),
  REQUIRED NUMBER(2),
  FORECASTED  NUMBER(2),
  FA_REJECTION_CODE VARCHAR2(100),
  PENDING_REASON  VARCHAR2(100),
  PE_SLOT VARCHAR2(30),
  PE_PORT VARCHAR2(30),
  PE_ODF VARCHAR2(100),
  CONNECTION_TFR_ID VARCHAR2(16),
  DISCONNECTED_TFR_ID VARCHAR2(16),
  CREATED_BY VARCHAR2(64),
  CWO_TYPE VARCHAR2(100),
  TFR_TYPE VARCHAR2(100),
  CURRENT_USERID VARCHAR2(64),
  PROJECT VARCHAR2(100),
  ROUTING_DETAILS VARCHAR2(4000),
  MAPPING_STATUS VARCHAR2(100),
  CUSTOMER_ADDRESS VARCHAR2(400),
  ORDER_NUMBER VARCHAR2(100),
  CIRCUIT_NUMBER VARCHAR2(100),
  GSM_CELL_ID VARCHAR2(100),
  MSAN_SITE_ID VARCHAR2(100),
  REJECTION_CODE VARCHAR2(100),
  FA_COMPLETION_DATE DATE,
  CUSTOMER_EXPD_DATE DATE,
  NI_NUMBER VARCHAR2(9),
  TFRYEAR VARCHAR2(4),
  TFRMONTH VARCHAR2(2),
  PARENT_PROC_ID VARCHAR2(16),
  REVISION NUMBER(10),
 	CWDOCSTAMP VARCHAR2(9),
 	CWORDERCREATIONDATE DATE,
 	CWORDERID VARCHAR2(16),
 	CWPARENTID VARCHAR2(16),
 	LASTUPDATEDDATE DATE,
 	UPDATEDBY VARCHAR2(64),
 	CANCELLED_DATE DATE,
  CURRENT_USER_DEPARTMENT VARCHAR2(100)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_TFR
ADD CONSTRAINT PK_STC_TFR PRIMARY KEY(TFR_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

ALTER TABLE STC_TFR
ADD CONSTRAINT UK_STC_TFR_NUMBER UNIQUE(TFR_NUMBER)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

ALTER TABLE STC_TFR
ADD CONSTRAINT FK_STC_TFR_PRN_ID FOREIGN KEY(PRN_ID)
REFERENCES STC_PRN (PRN_ID);

ALTER TABLE STC_PRN
ADD CONSTRAINT FK_STC_PRN_TFR_ID FOREIGN KEY(TFR_ID)
REFERENCES STC_TFR (TFR_ID);

ALTER TABLE STC_TFR
ADD CONSTRAINT FK_STC_TFR_CONN_TFR_ID FOREIGN KEY(CONNECTION_TFR_ID)
REFERENCES STC_TFR (TFR_ID);

ALTER TABLE STC_TFR
ADD CONSTRAINT FK_STC_TFR_DISCONN_TFR_ID FOREIGN KEY(DISCONNECTED_TFR_ID)
REFERENCES STC_TFR (TFR_ID);

CREATE TABLE STC_TFR_CUSTOMATTR (
  TFR_ID VARCHAR2(16) NOT NULL,
  CUSTOMATTR_ID VARCHAR2(16) NOT NULL,
  ATTRIBUTE_VALUE VARCHAR2(1000)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_TFR_CUSTOMATTR
ADD CONSTRAINT PK_STC_TFR_CUSTOMATTR PRIMARY KEY(TFR_ID, CUSTOMATTR_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

ALTER TABLE STC_TFR_CUSTOMATTR
ADD CONSTRAINT FK_STC_TFR_CUSTOMATTR_TFR FOREIGN KEY(TFR_ID)
REFERENCES STC_TFR (TFR_ID);

ALTER TABLE STC_TFR_CUSTOMATTR
ADD CONSTRAINT FK_STC_TFR_CUSTOMATTR_CATTR FOREIGN KEY(CUSTOMATTR_ID)
REFERENCES STC_CUSTOMATTR (CUSTOMATTR_ID);


CREATE TABLE STC_TFR_REMARKS (
  CWDOCID VARCHAR2(16) NOT NULL,
  TFR_ID VARCHAR2(16) NOT NULL,
  CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
  USERID VARCHAR2(64) NOT NULL,
  REMARK_TEXT VARCHAR2(4000)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_TFR_REMARKS
ADD CONSTRAINT PK_STC_TFR_REMARKS PRIMARY KEY(CWDOCID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

ALTER TABLE STC_TFR_REMARKS
ADD CONSTRAINT FK_STC_TFR_REMARKS FOREIGN KEY(TFR_ID)
REFERENCES STC_TFR (TFR_ID);


CREATE TABLE STC_TFR_NUMBERGEN_LOCK (
  LOCK_ACQUIRED VARCHAR2(1) NOT NULL
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_TFR_NUMBERGEN_LOCK
ADD CONSTRAINT PK_STC_TFR_NUMBERGEN_LOCK PRIMARY KEY(LOCK_ACQUIRED)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;
