prompt Creating BI tables...

@define_variables.sql

CREATE TABLE STC_BI(
 BI_ID VARCHAR2(16) NOT NULL,
 RING_NAME VARCHAR2(200),
 SITE_NAME VARCHAR2(100),
 NETWORK_TYPE VARCHAR2(100),
 CODE VARCHAR2(100),
 DETAILS VARCHAR2(400),
 CATEGORY VARCHAR2(100),
 MOP1_STATUS VARCHAR2(100),
 MOP2_STATUS VARCHAR2(100),
 MOP3_STATUS VARCHAR2(100),
 MOP_NUMBER VARCHAR2(30),
 MOP_ISSUE_DATE DATE,
 MOP_ESTIMATED_DATE DATE,
 MOP_IMPL_STATUS VARCHAR2(100),
 MOP_IMPL_COMPL_DATE DATE,
 MOP_IMPL_ESTIM_DATE DATE,
 BI_STATUS VARCHAR2(100),
 NETWORK_STATUS VARCHAR2(100),
 LAST_FWD_DEPT VARCHAR2(100),
 LAST_FWD_ENG VARCHAR2(64),
 LAST_FWD_DATE DATE,
 CREATED_BY VARCHAR2(64),
 CREATION_DATE DATE,
 APPROVED_SOLUTION VARCHAR2(4000),
 SOW1_STATUS VARCHAR2(100),
 SOW2_STATUS VARCHAR2(100),
 SOW3_STATUS VARCHAR2(100),
 SOW_NUMBER VARCHAR2(30),
 SOW_ISSUE_DATE DATE,
 SOW_ESTIMATE_DATE DATE,
 CONTRACTOR1 VARCHAR2(100),
 CONTRACTOR2 VARCHAR2(100),
 CONTRACTOR3 VARCHAR2(100),
 DDF_A_NOTE VARCHAR2(4000),
 DDF_Z_NOTE VARCHAR2(4000),
 COMPLETION_DATE DATE,
 PAT_FORECAST_DATE DATE,
 PAT_ACTUAL_DATE DATE,
 CUSTOMER_NAME VARCHAR2(100),
 MOP_DESIGN_STATUS VARCHAR2(30),
 AREA_REGION VARCHAR2(100),
 SDH_CATEGORY VARCHAR2(100),
 SDH_DESCRIPTION VARCHAR2(4000),
 SLOT VARCHAR2(30),
 SDH_VENDOR VARCHAR2(30),
 JOB_ESTIMATED_DATE DATE,
 BI_MATERIAL_STATUS VARCHAR2(30),
 SECONDARY_OWNER VARCHAR2(100),
 BU_INITIATOR VARCHAR2(128),
 CURRENT_USER VARCHAR2(64),
 MATERIALS VARCHAR2(4000),
 CWDOCSTAMP VARCHAR2(9),
 CWORDERCREATIONDATE DATE,
 CWORDERID VARCHAR2(16),
 CWPARENTID VARCHAR2(16),
 LASTUPDATEDDATE DATE,
 UPDATEDBY VARCHAR2(64),
 PARENTPROCID VARCHAR2(16),
 COMPLETION_PROCESSED NUMBER(1) DEFAULT 0
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_BI
ADD CONSTRAINT PK_STC_BI PRIMARY KEY(BI_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;


CREATE TABLE STC_BI_RELATIONSHIP (
  BI_ID VARCHAR2(16) NOT NULL,
  SOURCE_PRN_ID VARCHAR2(16),
  SOURCE_TFR_ID VARCHAR2(16)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_BI_RELATIONSHIP
ADD CONSTRAINT FK_STC_BI_RELATIONSHIP FOREIGN KEY(BI_ID)
REFERENCES STC_BI(BI_ID);

CREATE INDEX IDX_BI_RELATIONSHIP_BI ON STC_BI_RELATIONSHIP (BI_ID) TABLESPACE &DEFAULT_TABLESPACE_INDEX;
CREATE INDEX IDX_BI_RELATIONSHIP_PRN ON STC_BI_RELATIONSHIP (SOURCE_PRN_ID) TABLESPACE &DEFAULT_TABLESPACE_INDEX;
CREATE INDEX IDX_BI_RELATIONSHIP_TFR ON STC_BI_RELATIONSHIP (SOURCE_TFR_ID) TABLESPACE &DEFAULT_TABLESPACE_INDEX;


CREATE TABLE STC_BI_CUSTOMATTR (
  BI_ID VARCHAR2(16) NOT NULL,
  CUSTOMATTR_ID VARCHAR2(16) NOT NULL,
  ATTRIBUTE_VALUE VARCHAR2(1000)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_BI_CUSTOMATTR
ADD CONSTRAINT PK_STC_BI_CUSTOMATTR PRIMARY KEY(BI_ID, CUSTOMATTR_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

ALTER TABLE STC_BI_CUSTOMATTR
ADD CONSTRAINT FK_STC_BI_CUSTOMATTR FOREIGN KEY(BI_ID)
REFERENCES STC_BI(BI_ID);

ALTER TABLE STC_BI_CUSTOMATTR
ADD CONSTRAINT FK_STC_BI_CUSTOMATTR_CATTR FOREIGN KEY(CUSTOMATTR_ID)
REFERENCES STC_CUSTOMATTR (CUSTOMATTR_ID);

CREATE TABLE STC_BI_NOTIFICATION (
  CWDOCID VARCHAR2(16) NOT NULL,
  BI_ID VARCHAR2(16) NOT NULL,
  WHEN_ADDED DATE DEFAULT SYSDATE NOT NULL
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_BI_NOTIFICATION
ADD CONSTRAINT PK_STC_BI_NOTIFICATION PRIMARY KEY(CWDOCID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;
