prompt Creating TASK table...

@define_variables.sql

CREATE TABLE STC_TFR_TASK(
  TFR_TASK_ID VARCHAR2(16) NOT NULL,
  TASK_NAME VARCHAR2(60),
  TASK_STATUS VARCHAR2(100),
  TFR_ID VARCHAR2(16),
  SITE_NAME VARCHAR2(100),
  SITE_IF VARCHAR2(100),
  SITE_JVC VARCHAR2(100),
  SITE_EXCHANGETYPE VARCHAR2(100),
  SITE_TERMINATION VARCHAR2(100),
  SITE_SWITCH_TYPE VARCHAR2(100),
  CREATION_DATE DATE,
  ACCEPT_DATE DATE,
  ASSIGN_SITE_TEAM_DATE DATE,
  ACCEPT_SITE_TEAM_DATE DATE,
  ASSIGN_QUALITY_TEAM_DATE DATE,
  ACCEPT_QUALITY_TEAM_DATE DATE,
  DESCRIPTION VARCHAR2(1000),
  SITE_TEAM_MEMBER_ACC VARCHAR2(64),
  QUALITY_TEAM_MEMBER_ACC VARCHAR2(64),
  CWDOCSTAMP VARCHAR2(9),
  CWORDERCREATIONDATE DATE,
  CWORDERID VARCHAR2(16),
  CWPARENTID VARCHAR2(16),
  LASTUPDATEDDATE DATE,
  UPDATEDBY VARCHAR2(64),
  PARENTPROCESSID VARCHAR2(16),
  ISEND2END NUMBER(1),
  TFRREVISION NUMBER(2)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_TFR_TASK
ADD CONSTRAINT PK_STC_TFR_TASK PRIMARY KEY(TFR_TASK_ID)
USING INDEX
TABLESPACE &DEFAULT_TABLESPACE_INDEX;

ALTER TABLE STC_TFR_TASK
ADD CONSTRAINT FK_STC_TFR_TASK_TFR_ID FOREIGN KEY(TFR_ID)
REFERENCES STC_TFR (TFR_ID);
