prompt Importing table STC_CUSTOMATTR...

insert into STC_CUSTOMATTR (CUSTOMATTR_ID, PARENT_ELEMENT, ATTRIBUTE_NAME, ATTRIBUTE_TYPE)
values ('1', 'PRNR', 'StringUDA', 'String');

insert into STC_CUSTOMATTR (CUSTOMATTR_ID, PARENT_ELEMENT, ATTRIBUTE_NAME, ATTRIBUTE_TYPE)
values ('2', 'PRNR', 'PickListUDA', 'PickList');

insert into STC_CUSTOMATTR (CUSTOMATTR_ID, PARENT_ELEMENT, ATTRIBUTE_NAME, ATTRIBUTE_TYPE)
values ('3', 'PRNR', 'DateUDA', 'Date');

insert into STC_CUSTOMATTR (CUSTOMATTR_ID, PARENT_ELEMENT, ATTRIBUTE_NAME, ATTRIBUTE_TYPE)
values ('4', 'PRN', 'StringUDA_PRN', 'String');

insert into STC_CUSTOMATTR (CUSTOMATTR_ID, PARENT_ELEMENT, ATTRIBUTE_NAME, ATTRIBUTE_TYPE)
values ('5', 'PRN', 'PickList_UDA_PRN', 'PickList');

insert into STC_CUSTOMATTR (CUSTOMATTR_ID, PARENT_ELEMENT, ATTRIBUTE_NAME, ATTRIBUTE_TYPE)
values ('6', 'PRN', 'DateUDA_PRN', 'Date');

insert into STC_CUSTOMATTR (CUSTOMATTR_ID, PARENT_ELEMENT, ATTRIBUTE_NAME, ATTRIBUTE_TYPE)
values ('7', 'TFR', 'StringUDA_TFR', 'String');

insert into STC_CUSTOMATTR (CUSTOMATTR_ID, PARENT_ELEMENT, ATTRIBUTE_NAME, ATTRIBUTE_TYPE)
values ('8', 'TFR', 'PickList_UDA_TFR', 'PickList');

insert into STC_CUSTOMATTR (CUSTOMATTR_ID, PARENT_ELEMENT, ATTRIBUTE_NAME, ATTRIBUTE_TYPE)
values ('9', 'TFR', 'DateUDA_TFR', 'Date');

insert into STC_CUSTOMATTR (CUSTOMATTR_ID, PARENT_ELEMENT, ATTRIBUTE_NAME, ATTRIBUTE_TYPE)
values ('10', 'BI', 'StringUDA_BI', 'String');

insert into STC_CUSTOMATTR (CUSTOMATTR_ID, PARENT_ELEMENT, ATTRIBUTE_NAME, ATTRIBUTE_TYPE)
values ('11', 'BI', 'PickList_UDA_BI', 'PickList');

insert into STC_CUSTOMATTR (CUSTOMATTR_ID, PARENT_ELEMENT, ATTRIBUTE_NAME, ATTRIBUTE_TYPE)
values ('12', 'BI', 'DateUDA_BI', 'Date');

insert into STC_CUSTOMATTR (CUSTOMATTR_ID, PARENT_ELEMENT, ATTRIBUTE_NAME, ATTRIBUTE_TYPE, HYPERLINK_ATTR_NAME)
values ('13', 'PRNR', 'Test for HyperLink', 'Hyperlink', 'PRNR_NAME');

commit;
