prompt Importing table STC_CUSTOMATTR_LIST_OPTION...

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('1', '2', 'Alpha', 1);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('2', '2', 'Beta', 2);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('3', '2', 'Gamma', 3);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('4', '2', 'Delta', 4);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('5', '2', 'Eta', 5);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('6', '5', '1', 1);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('7', '5', '2', 2);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('8', '5', '3', 3);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('9', '5', '4', 4);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('10', '8', 'A', 1);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('11', '8', 'B', 2);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('12', '8', 'C', 3);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('13', '11', '000', 1);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('14', '11', '001', 2);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('15', '11', '010', 3);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('16', '11', '011', 4);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('17', '11', '100', 5);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('18', '11', '101', 6);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('19', '11', '110', 7);

insert into STC_CUSTOMATTR_LIST_OPTION (CWDOCID, CUSTOMATTR_ID, ATTRIBUTE_VALUE, SEQUENCE_NUMBER)
values ('20', '11', '111', 8);

commit;
