prompt Importing table STC_REJECT_QUESTION and STC_REJECT_ANSWER ...

insert into STC_REJECT_QUESTION (QUESTION_ID, PARENT_ANSWER_ID, TEXT_QUESTION)
values ('1', null, 'Question 1');

insert into STC_REJECT_ANSWER (ANSWER_ID, PARENT_QUESTION_ID, TEXT_ANSWER, RESPONSE_TO_RETURN)
values ('1.1', '1', 'Answer 1.1', null);

insert into STC_REJECT_ANSWER (ANSWER_ID, PARENT_QUESTION_ID, TEXT_ANSWER, RESPONSE_TO_RETURN)
values ('1.2', '1', 'Answer 1.2', null);

insert into STC_REJECT_QUESTION (QUESTION_ID, PARENT_ANSWER_ID, TEXT_QUESTION)
values ('1.1.1', '1.1', 'Question 1.1.1');

insert into STC_REJECT_ANSWER (ANSWER_ID, PARENT_QUESTION_ID, TEXT_ANSWER, RESPONSE_TO_RETURN)
values ('1.1.1.1', '1.1.1', 'Answer 1.1.1.1', 'Tx DDF occupied');

insert into STC_REJECT_ANSWER (ANSWER_ID, PARENT_QUESTION_ID, TEXT_ANSWER, RESPONSE_TO_RETURN)
values ('1.1.1.2', '1.1.1', 'Answer 1.1.1.2', null);

insert into STC_REJECT_QUESTION (QUESTION_ID, PARENT_ANSWER_ID, TEXT_QUESTION)
values ('1.2.1', '1.2', 'Question 1.2.1');

insert into STC_REJECT_ANSWER (ANSWER_ID, PARENT_QUESTION_ID, TEXT_ANSWER, RESPONSE_TO_RETURN)
values ('301001', '1.2.1', 'Answer 1.2.1.2', 'Tx DDF occupied');

insert into STC_REJECT_ANSWER (ANSWER_ID, PARENT_QUESTION_ID, TEXT_ANSWER, RESPONSE_TO_RETURN)
values ('301002', '1.2.1', 'Answe 1.2.1.3', null);

insert into STC_REJECT_QUESTION (QUESTION_ID, PARENT_ANSWER_ID, TEXT_QUESTION)
values ('303000', '301002', 'Question 1.2.1.2.1');

commit;