prompt Importing table STC_CITY_DISTRICT_REGION ...

insert into STC_CITY_DISTRICT_REGION (CITY_NAME, DISTRICT_NAME, REGION_CODE)
values ('AR RADFAYN', 'HAIL', '01');

insert into STC_CITY_DISTRICT_REGION (CITY_NAME, DISTRICT_NAME, REGION_CODE)
values ('RUDUMAH', 'RIYADHDISTRICTS', '03');

insert into STC_CITY_DISTRICT_REGION (CITY_NAME, DISTRICT_NAME, REGION_CODE)
values ('MADINAH', 'MADINAH', '11');

insert into STC_CITY_DISTRICT_REGION (CITY_NAME, DISTRICT_NAME, REGION_CODE)
values ('MAKKAH', 'MAKKAH', '04');

commit;
