CREATE SEQUENCE stc_migration_log_seq 
MINVALUE 1
MAXVALUE 999999999999
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE TABLE stc_migration_log (
  log_id NUMBER(9) NOT NULL,
  log_date DATE DEFAULT SYSDATE NOT NULL,
  log_message VARCHAR2(4000)
);  
