-- MANDATORY NV Pairs
insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'F', 'IP',   'MW Option' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'F', 'DIA',  'MW Option' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'F', 'MDIA', 'MW Option' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'F', 'DIAS', 'MW Option' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'F', 'SIP',  'MW Option' from STC_NVNAMES_MANDATORY;

insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'I', 'IP',   'MW Option' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'I', 'DIA',  'MW Option' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'I', 'MDIA', 'MW Option' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'I', 'DIAS', 'MW Option' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'I', 'SIP',  'MW Option' from STC_NVNAMES_MANDATORY;

insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'C', 'IP',   'MW Option' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'C', 'DIA',  'MW Option' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'C', 'MDIA', 'MW Option' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'C', 'DIAS', 'MW Option' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY (CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select (max(to_number(CWDOCID)) + 1), 'C', 'SIP',  'MW Option' from STC_NVNAMES_MANDATORY;

commit;

-- NV Pair picklist
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('IP',   'MW Option', 'Yes');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('IP',   'MW Option', 'No');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('DIA',  'MW Option', 'Yes');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('DIA',  'MW Option', 'No');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('MDIA', 'MW Option', 'Yes');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('MDIA', 'MW Option', 'No');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('DIAS', 'MW Option', 'Yes');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('DIAS', 'MW Option', 'No');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('SIP',  'MW Option', 'Yes');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('SIP',  'MW Option', 'No');

insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('IP',   'MW Option Type', 'PTP');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('IP',   'MW Option Type', 'PTMP');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('DIA',  'MW Option Type', 'PTP');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('DIA',  'MW Option Type', 'PTMP');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('MDIA', 'MW Option Type', 'PTP');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('MDIA', 'MW Option Type', 'PTMP');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('DIAS', 'MW Option Type', 'PTP');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('DIAS', 'MW Option Type', 'PTMP');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('SIP',  'MW Option Type', 'PTP');
insert into STC_NVPAIR_SERVTYPE_PICKLIST (SERVICETYPE, NVPAIR_NAME, VALUE) values('SIP',  'MW Option Type', 'PTMP');

commit;

