alter table STCW_LINEITEM add ISVAS NUMBER(1);

update STCW_LINEITEM set ISVAS = 0;
commit;

alter table STCW_SERVICETYPES_HIERARCHY add TASK_OPERATION VARCHAR2(255);
alter table STCW_SERVICETYPES_HIERARCHY add IS_SIBLING NUMBER(1);

alter table STCW_SERVICETYPES_HIERARCHY add constraint UK_SERVICETYPES_HIERARCHY unique (PARENT_SERVICETYPE, CHILD_SERVICETYPE) ;

update STCW_SERVICETYPES_HIERARCHY set TASK_OPERATION = null, IS_SIBLING=1;
commit;

