-- STCW_PICKLIST_FOR_VALIDATION - VAS
insert into STCW_PICKLIST_FOR_VALIDATION(CWDOCID, DATATYPENAME, VALUE)
  select max(to_number(CWDOCID) + 1) , 'lineItemType', 'VAS'
    from STCW_PICKLIST_FOR_VALIDATION;

    
-- STCW_PRODUCTCODE - V006 /**** TO SET THE PROPER VALUE ****/
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS, IS_VPN)
values ('V006', 1, 'ALL_OR_NOTHING', 0, 0);
   

-- STCW_PRODUCTCODE for IGNET (I or N) and IP-TRANSIT
update STCW_PRODUCTCODE set FEAS_APPROACH='ALL_OR_NOTHING' where PRODUCTCODE in ('D15N', 'D15I', 'D016');

-- STCW_SERVICETYPE_NAME_MAPPING - DDOS /**** TO SET THE PROPER VALUE ****/
insert into STCW_SERVICETYPE_NAME_MAP(COM_SERVICETYPE, GI_SERVICETYPE)
values ('V006', 'DDoS');


-- STCW_SERVICETYPES_HIERARCHY - D15N -> DDOS /**** TO SET THE PROPER VALUE ****/
insert into STCW_SERVICETYPES_HIERARCHY(CWDOCID, PARENT_SERVICETYPE, CHILD_SERVICETYPE, TASK_OPERATION, IS_SIBLING)
  select max(to_number(CWDOCID) + 1) , 'D15N', 'V006', 'W-E2E_TEST', 0
    from STCW_SERVICETYPES_HIERARCHY;

-- STCW_SERVICETYPES_HIERARCHY - D15I -> DDOS /**** TO SET THE PROPER VALUE ****/
insert into STCW_SERVICETYPES_HIERARCHY(CWDOCID, PARENT_SERVICETYPE, CHILD_SERVICETYPE, TASK_OPERATION, IS_SIBLING)
  select max(to_number(CWDOCID) + 1) , 'D15I', 'V006', 'W-E2E_TEST', 0
    from STCW_SERVICETYPES_HIERARCHY;
    
-- STCW_SERVICETYPES_HIERARCHY - D016 -> DDOS /**** TO SET THE PROPER VALUE ****/
insert into STCW_SERVICETYPES_HIERARCHY(CWDOCID, PARENT_SERVICETYPE, CHILD_SERVICETYPE, TASK_OPERATION, IS_SIBLING)
  select max(to_number(CWDOCID) + 1) , 'D016', 'V006', 'W-E2E_TEST', 0
    from STCW_SERVICETYPES_HIERARCHY;

-- STCW_BU_PROVISIONING - D15N -> DDOS /**** TO SET THE PROPER VALUE ****/
insert into STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM) values ('V006', 'D15N', 'W');

-- STCW_BU_PROVISIONING - D15I -> DDOS /**** TO SET THE PROPER VALUE ****/
insert into STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM) values ('V006', 'D15I', 'W');

-- STCW_BU_PROVISIONING - D016 -> DDOS /**** TO SET THE PROPER VALUE ****/
insert into STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM) values ('V006', 'D016', 'W');


commit;
