alter table STCW_LINEITEM drop column ISVAS;

alter table STCW_SERVICETYPES_HIERARCHY drop column TASK_OPERATION;
alter table STCW_SERVICETYPES_HIERARCHY drop column IS_SIBLING;

delete from STCW_PICKLIST_FOR_VALIDATION where DATATYPENAME = 'lineItemType' and VALUE = 'VAS';
delete from STCW_PRODUCTCODE where PRODUCTCODE = 'V006'; 
delete from STCW_SERVICETYPE_NAME_MAP where COM_SERVICETYPE = 'V006';
delete from STCW_SERVICETYPES_HIERARCHY where CHILD_SERVICETYPE = 'V006';
delete from STCW_BU_PROVISIONING where SERVICETYPE = 'V006';

commit;
