insert into STC_SERVICETYPE_BEHAVIORCONFIG (SERVICETYPE, EXTERNAL_VALIDATION_REQUIRED, SEND_DISCONNECT_FOR_CANCEL, SUPPORT_PROVISIONING, SUPPORT_PARTIAL_CANCEL, DISCONNECT_4_NVP_EXISTCIRCUIT, REQUIRE_AUTODESIGN) values ('SAT', 1, 0, 1, 1, 0, 1);
insert into STC_SERVICETYPE_BEHAVIORCONFIG (SERVICETYPE, EXTERNAL_VALIDATION_REQUIRED, SEND_DISCONNECT_FOR_CANCEL, SUPPORT_PROVISIONING, SUPPORT_PARTIAL_CANCEL, DISCONNECT_4_NVP_EXISTCIRCUIT, REQUIRE_AUTODESIGN) values ('SATPtP', 1, 0, 1, 1, 0, 1);
insert into STC_SERVICETYPE_BEHAVIORCONFIG (SERVICETYPE, EXTERNAL_VALIDATION_REQUIRED, SEND_DISCONNECT_FOR_CANCEL, SUPPORT_PROVISIONING, SUPPORT_PARTIAL_CANCEL, DISCONNECT_4_NVP_EXISTCIRCUIT, REQUIRE_AUTODESIGN) values ('SATIP', 1, 0, 1, 1, 0, 1);
insert into STC_SERVICETYPE_BEHAVIORCONFIG (SERVICETYPE, EXTERNAL_VALIDATION_REQUIRED, SEND_DISCONNECT_FOR_CANCEL, SUPPORT_PROVISIONING, SUPPORT_PARTIAL_CANCEL, DISCONNECT_4_NVP_EXISTCIRCUIT, REQUIRE_AUTODESIGN) values ('SATNET', 1, 0, 1, 1, 0, 1);
insert into STC_SERVICETYPE_BEHAVIORCONFIG (SERVICETYPE, EXTERNAL_VALIDATION_REQUIRED, SEND_DISCONNECT_FOR_CANCEL, SUPPORT_PROVISIONING, SUPPORT_PARTIAL_CANCEL, DISCONNECT_4_NVP_EXISTCIRCUIT, REQUIRE_AUTODESIGN) values ('SATMHz', 1, 0, 1, 1, 0, 1);
insert into STC_SERVICETYPE_BEHAVIORCONFIG (SERVICETYPE, EXTERNAL_VALIDATION_REQUIRED, SEND_DISCONNECT_FOR_CANCEL, SUPPORT_PROVISIONING, SUPPORT_PARTIAL_CANCEL, DISCONNECT_4_NVP_EXISTCIRCUIT, REQUIRE_AUTODESIGN) values ('MVPN', 1, 0, 1, 1, 0, 1);

update STC_SERVICETYPE_BEHAVIORCONFIG set REQUIRE_AUTODESIGN = 1 where SERVICETYPE = 'ATMMVPN';

commit;