insert into STC_NVPAIR_SERVTYPE_PICKLIST(SERVICETYPE, NVPAIR_NAME, VALUE) values ('APN', 'APN Type', 'Mobile');
insert into STC_NVPAIR_SERVTYPE_PICKLIST(SERVICETYPE, NVPAIR_NAME, VALUE) values ('APN', 'APN Type', 'M2M');

insert into STC_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'F', 'APN', 'APN Type' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'I', 'APN', 'APN Type' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'C', 'APN', 'APN Type' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'T', 'APN', 'APN Type' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'D', 'APN', 'APN Type' from STC_NVNAMES_MANDATORY;
insert into STC_NVNAMES_MANDATORY(CWDOCID, ORDERTYPE, SERVICETYPE, NAMENVPAIR) select max(to_number(cwdocid)) + 1, 'E', 'APN', 'APN Type' from STC_NVNAMES_MANDATORY;

commit;
