-- THIS ONE HAS TO BE EXECUTED AS CWE_DOWNGRADE

create table STC_BUNDLEORDER_HEADER
  as select * from CWE_BUNDLE.STC_BUNDLEORDER_HEADER where rownum < 1;
create index DWN_STC_BO_HEADER_CWORDERID on STC_BUNDLEORDER_HEADER (CWORDERID);
create index DWN_STC_BO_HEADER_ORDERNUMBER on STC_BUNDLEORDER_HEADER (ORDERNUMBER);
create index DWN_PK_STC_BUNDLEORDER_HEADER on STC_BUNDLEORDER_HEADER (CWDOCID);


create table STC_LINEITEM
  as select * from CWE_BUNDLE.STC_LINEITEM where rownum < 1;
create index DWN_STC_LINEITEM_CWORDERID on STC_LINEITEM (CWORDERID);
create index DWN_STC_LINEITEM_LIIDENTIFIER on STC_LINEITEM (LINEITEMIDENTIFIER);
create index DWN_PK_STC_LINEITEM on STC_LINEITEM (CWDOCID);


create table STC_NAME_VALUE
  as select * from CWE_BUNDLE.STC_NAME_VALUE where rownum < 1;
create index DWN_PK_STC_NAME_VALUE on STC_NAME_VALUE (CWDOCID);
create index DWN_ORD_STC_NVALUE_CWORDERID on STC_NAME_VALUE (CWORDERID);


create table CWORDERINSTANCE
  as select * from CWE_BUNDLE.CWORDERINSTANCE where rownum < 1;
create index DWN_CWFPK_ORDINST on CWORDERINSTANCE (CWDOCID);


create table CWORDERITEMS
  as select * from CWE_BUNDLE.CWORDERITEMS where rownum < 1;
create index DWN_CWORDERITEMS_ORDID on CWORDERITEMS (TOPORDERID);
create index DWN_CWORDERITEMS_ITEMID on CWORDERITEMS (ITEMID);
  
  
create table STC_PRODUCTTYPE_NAME_MAP
  as select * from CWE_BUNDLE.STC_PRODUCTTYPE_NAME_MAP where rownum < 1;


