alter table STC_LINEITEM add PARKPROVISIONING NUMBER(1) DEFAULT 0;
alter table STC_LINEITEM add RESUMEPROVISIONING NUMBER(1) DEFAULT 0;

alter table STC_DEL_LINEITEM add PARKPROVISIONING NUMBER(1) DEFAULT 0;
alter table STC_DEL_LINEITEM add RESUMEPROVISIONING NUMBER(1) DEFAULT 0;
