define DEFAULT_TABLESPACE_TABLE = CWE;
define DEFAULT_TABLESPACE_INDEX = CWE_NDX;

CREATE TABLE STC_NEWATTR_NVPAIR(
	NAME VARCHAR2(100) NOT NULL,
	CONSTRAINT PK_STC_NEWATTR_NVPAIR PRIMARY KEY(NAME) USING INDEX
	(CREATE UNIQUE INDEX PK_STC_NEWATTR_NVPAIR ON STC_NEWATTR_NVPAIR(NAME) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

CREATE TABLE STC_SKIP_NVPAIR(
	NAME VARCHAR2(100) NOT NULL,
	CONSTRAINT PK_STC_SKIP_NVPAIR PRIMARY KEY(NAME) USING INDEX
	(CREATE UNIQUE INDEX PK_STC_SKIP_NVPAIR ON STC_SKIP_NVPAIR(NAME) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;


INSERT INTO STC_NEWATTR_NVPAIR VALUES('Account Mgr Contact');
INSERT INTO STC_NEWATTR_NVPAIR VALUES('Account Mgr ID');
INSERT INTO STC_NEWATTR_NVPAIR VALUES('Account Mgr Name');


INSERT INTO STC_SKIP_NVPAIR VALUES('VCI Site A');
INSERT INTO STC_SKIP_NVPAIR VALUES('VCI Site B');
INSERT INTO STC_SKIP_NVPAIR VALUES('VPI Site A');
INSERT INTO STC_SKIP_NVPAIR VALUES('VPI Site B');
INSERT INTO STC_SKIP_NVPAIR VALUES('DSL EL Site A');
INSERT INTO STC_SKIP_NVPAIR VALUES('DSL EL Site B');
INSERT INTO STC_SKIP_NVPAIR VALUES('DSL EN Site A');
INSERT INTO STC_SKIP_NVPAIR VALUES('DSL EN Site B');
INSERT INTO STC_SKIP_NVPAIR VALUES('DSL Switch Site A');
INSERT INTO STC_SKIP_NVPAIR VALUES('DSL Switch Site B');
INSERT INTO STC_SKIP_NVPAIR VALUES('Switch Type Site A');
INSERT INTO STC_SKIP_NVPAIR VALUES('Switch Type Site B');
INSERT INTO STC_SKIP_NVPAIR VALUES('Product Type');
INSERT INTO STC_SKIP_NVPAIR VALUES('Speeds');
INSERT INTO STC_SKIP_NVPAIR VALUES('MRS');
INSERT INTO STC_SKIP_NVPAIR VALUES('DDN Main Access Type A');
INSERT INTO STC_SKIP_NVPAIR VALUES('DDN Main Access Type B');
INSERT INTO STC_SKIP_NVPAIR VALUES('DDN NRC_DDN Main Access Type A');
INSERT INTO STC_SKIP_NVPAIR VALUES('DDN NRC_DDN Main Access Type B');
INSERT INTO STC_SKIP_NVPAIR VALUES('DDN_DDN Main Access Type A');
INSERT INTO STC_SKIP_NVPAIR VALUES('DDN_DDN Main Access Type B');
INSERT INTO STC_SKIP_NVPAIR VALUES('SD DDN General Information_Order Type');
INSERT INTO STC_SKIP_NVPAIR VALUES('Priority');


COMMIT;
