define DEFAULT_TABLESPACE_TABLE = CWE;
define DEFAULT_TABLESPACE_INDEX = CWE_NDX;


-- Create sequence 
CREATE SEQUENCE stc_custom_log_id
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;


CREATE TABLE stc_updateCCLI_log (
  logid      NUMBER(16) NOT NULL,
	cworderid  VARCHAR2(16) NOT NULL,
	cwdocid    VARCHAR2(16) NOT NULL,
	old_A_CCLI VARCHAR2(50),
	old_Z_CCLI VARCHAR2(50),
	new_A_CCLI VARCHAR2(50),
	new_Z_CCLI VARCHAR2(50),
	errorMsg   VARCHAR2(1000),
	CONSTRAINT PK_STC_UPDCCLI_LOG PRIMARY KEY(logid) USING INDEX
	(CREATE UNIQUE INDEX PK_STC_UPDCCLI_LOG ON stc_updateCCLI_log(logid) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;


