define DEFAULT_TABLESPACE_TABLE = CWE;
define DEFAULT_TABLESPACE_INDEX = CWE_NDX;


-- Create configuration table for block parameters
CREATE TABLE CWE.STC_BLOCKPARAMS_CONFIGURATION(
	CWDOCID VARCHAR2(16) NOT NULL,
	ISMANDATORY NUMBER(1),
	BLOCKPARAMETERNAME VARCHAR2(4000),
	ORDERSTATUS VARCHAR2(50),
	SERVICETYPE VARCHAR2(25),
	ORDERTYPE VARCHAR2(25),
	CONSTRAINT PK_STC_BLOCKPARAMS_CONFIGURATI PRIMARY KEY(CWDOCID) USING INDEX
	(CREATE UNIQUE INDEX PK_STC_BLOCKPARAMS_CONFIGURATI ON STC_BLOCKPARAMS_CONFIGURATION(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

COMMIT;


