define DEFAULT_TABLESPACE_TABLE = CWE;
define DEFAULT_TABLESPACE_INDEX = CWE_NDX;

--Adding SCANMODE for a line item
ALTER TABLE STC_LINEITEM
ADD (
	SCANMODE VARCHAR2(12));

ALTER TABLE STC_DEL_LINEITEM
ADD (
	SCANMODE VARCHAR2(12));
	
COMMIT;
