define DEFAULT_TABLESPACE_TABLE = CWE;
define DEFAULT_TABLESPACE_INDEX = CWE_NDX;


CREATE TABLE STC_PRODTYPE_SCAN_CFG(
	CWDOCID VARCHAR2(16) NOT NULL,
	PRODUCTTYPE VARCHAR2(255),
	SERVICETYPE VARCHAR2(25),
	REASONCODE VARCHAR2(1000),
	SCANTOPDOWN NUMBER(1),
	CONSTRAINT PK_STC_PRODTYPE_SCAN_CFG PRIMARY KEY(CWDOCID) USING INDEX
	(CREATE UNIQUE INDEX PK_STC_PRODTYPE_SCAN_CFG ON STC_PRODTYPE_SCAN_CFG(CWDOCID) TABLESPACE &DEFAULT_TABLESPACE_INDEX)
)
TABLESPACE &DEFAULT_TABLESPACE_TABLE;

ALTER TABLE STC_PRODTYPE_SCAN_CFG
  ADD CONSTRAINT UK_PROD_SCAN_PRODTYPE_REASCODE UNIQUE (PRODUCTTYPE, SERVICETYPE, REASONCODE)
  USING INDEX;

COMMIT;