set JAVA_HOME=C:\Program Files\Java\jdk1.7.0_75

set ORDER_GENERATION_HOME=C:\development\STC\16.0\GRAN-551\orderGeneration
set ORDER_GENERATION_CONFIG=%ORDER_GENERATION_HOME%\config
set ORDER_GENERATION_LIB=%ORDER_GENERATION_HOME%\lib
set ORDER_GENERATION_LOG4J=%ORDER_GENERATION_LIB%\log4j\log4j.jar
set ORDER_GENERATION_ORACLE=%ORDER_GENERATION_LIB%\oracle\ojdbc6.jar;%ORDER_GENERATION_LIB%\oracle\orai18n.jar;%ORDER_GENERATION_LIB%\oracle\orai18n-mapping.jar
set ORDER_GENERATION_XPATH=%ORDER_GENERATION_LIB%\xpath\commons-jxpath-1.3.jar

set ORDER_GENERATION_CLASSPATH=%ORDER_GENERATION_HOME%;%ORDER_GENERATION_HOME%\orderGeneration.jar;%ORDER_GENERATION_LOG4J%;%ORDER_GENERATION_ORACLE%;%ORDER_GENERATION_XPATH%;%ORDER_GENERATION_CONFIG%

"%JAVA_HOME%\bin\java" -classpath "%ORDER_GENERATION_CLASSPATH%" com.ericsson.stc.orderGeneration.OrderGeneratorTool
