alter table STCW_PRODUCTCODE
  drop constraint FEAS_APPROACH_VALUES;
  
alter table STCW_PRODUCTCODE
  add constraint FEAS_APPROACH_VALUES
  check (FEAS_APPROACH in ('DEFAULT', 'ALL_OR_NOTHING', 'SERVICETYPES_RESULT'));

alter table STCW_PRODUCTCODE add SUPPORT_FEASIBILITY NUMBER(1) DEFAULT 1;
