insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS, IS_VPN, IS_PROVISIONABLE, SUPPORT_FEASIBILITY) 
  values ('D060', 1, 'SERVICETYPES_RESULT', 0, 0, 1, 0);
insert into STCW_PRODUCTCODE(PRODUCTCODE, SEND_DISCONNECT_FOR_CANCEL, FEAS_APPROACH, REQUIRE_VALIDATION_BOS, IS_VPN, IS_PROVISIONABLE, SUPPORT_FEASIBILITY) 
  values ('D061', 0, 'DEFAULT', 0, 0, 1, 0);

commit;
