insert into STCW_ST_RES_FEAS_APPROACH(CWDOCID, BUNDLE_PRODUCTCODE, LI_PRODUCTCODE) values (1, 'D060', 'D060');
insert into STCW_ST_RES_FEAS_APPROACH(CWDOCID, BUNDLE_PRODUCTCODE, LI_PRODUCTCODE) values (2, 'D060', 'D061');

commit;
