insert into STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM) values ('D060', 'D060', 'W');
insert into STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM) values ('D061', 'D060', 'W');
insert into STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM) values ('C032', 'D060', 'W');
insert into STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM) values ('C033', 'D060', 'W');
insert into STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM) values ('C034', 'D060', 'W');
insert into STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM) values ('C035', 'D060', 'W');
insert into STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM) values ('D052', 'D060', 'E');
insert into STCW_BU_PROVISIONING (SERVICETYPE, PRODUCTCODE, CIM) values ('D053', 'D060', 'E');

commit;