insert into STCW_SERVICETYPE_NAME_MAP (COM_SERVICETYPE, GI_SERVICETYPE, SOM_INTERNALNAME) values ('D060', 'D060', null);
insert into STCW_SERVICETYPE_NAME_MAP (COM_SERVICETYPE, GI_SERVICETYPE, SOM_INTERNALNAME) values ('D061', 'D061', null);

commit;